with open('src/services/footballData.ts', encoding='utf-8') as f:
    content = f.read()

r16_lineups = '''
  // Round of 16
  "Canada_Morocco": {
    homeTeam: "Canada", awayTeam: "Morocco",
    homeFormation: "4-4-2", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Maxime Crépeau",number:16,position:"GK"},
      {id:2,name:"Alistair Johnston",number:2,position:"RB"},
      {id:3,name:"Moïse Bombito",number:15,position:"CB"},
      {id:4,name:"Luc de Fougerolles",number:4,position:"CB"},
      {id:5,name:"Richie Laryea",number:22,position:"LB"},
      {id:6,name:"Tajon Buchanan",number:17,position:"RM"},
      {id:7,name:"Niko Sigur",number:23,position:"CM"},
      {id:8,name:"Stephen Eustáquio",number:7,position:"CM"},
      {id:9,name:"Ali Ahmed",number:26,position:"LM"},
      {id:10,name:"Jonathan David",number:10,position:"CF"},
      {id:11,name:"Tani Oluwaseyi",number:12,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Alphonso Davies",number:19,position:"DF"},
      {id:13,name:"Jacob Shaffelburg",number:14,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Yassine Bounou",number:1,position:"GK"},
      {id:21,name:"Achraf Hakimi",number:2,position:"RB"},
      {id:22,name:"Issa Diop",number:14,position:"CB"},
      {id:23,name:"Redouane Halhal",number:5,position:"CB"},
      {id:24,name:"Noussair Mazraoui",number:3,position:"LB"},
      {id:25,name:"Ayyoub Bouaddi",number:6,position:"CM"},
      {id:26,name:"Neil El Aynaoui",number:24,position:"CM"},
      {id:27,name:"Brahim Díaz",number:10,position:"RW"},
      {id:28,name:"Azzedine Ounahi",number:8,position:"AM"},
      {id:29,name:"Bilal El Khannouss",number:23,position:"LW"},
      {id:30,name:"Ismael Saibari",number:11,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Soufiane Rahimi",number:9,position:"FW"},
      {id:32,name:"Chemsdine Talbi",number:7,position:"MF"},
    ],
  },
  "Paraguay_France": {
    homeTeam: "Paraguay", awayTeam: "France",
    homeFormation: "4-4-2", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Orlando Gill",number:12,position:"GK"},
      {id:2,name:"Juan José Cáceres",number:4,position:"RB"},
      {id:3,name:"Gustavo Gómez",number:15,position:"CB"},
      {id:4,name:"José Canale",number:13,position:"CB"},
      {id:5,name:"Júnior Alonso",number:6,position:"LB"},
      {id:6,name:"Maurício",number:11,position:"RM"},
      {id:7,name:"Andrés Cubas",number:14,position:"CM"},
      {id:8,name:"Matías Galarza",number:23,position:"CM"},
      {id:9,name:"Gustavo Caballero",number:24,position:"LM"},
      {id:10,name:"Antonio Sanabria",number:9,position:"CF"},
      {id:11,name:"Julio Enciso",number:19,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Gabriel Ávalos",number:21,position:"FW"},
      {id:13,name:"Damián Bobadilla",number:16,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Mike Maignan",number:16,position:"GK"},
      {id:21,name:"Jules Koundé",number:5,position:"RB"},
      {id:22,name:"Dayot Upamecano",number:4,position:"CB"},
      {id:23,name:"William Saliba",number:17,position:"CB"},
      {id:24,name:"Lucas Digne",number:3,position:"LB"},
      {id:25,name:"Aurélien Tchouaméni",number:8,position:"CM"},
      {id:26,name:"Adrien Rabiot",number:14,position:"CM"},
      {id:27,name:"Ousmane Dembélé",number:7,position:"RW"},
      {id:28,name:"Michael Olise",number:11,position:"AM"},
      {id:29,name:"Bradley Barcola",number:12,position:"LW"},
      {id:30,name:"Kylian Mbappé",number:10,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Désiré Doué",number:20,position:"FW"},
      {id:32,name:"Rayan Cherki",number:24,position:"MF"},
    ],
  },
  "Brazil_Norway": {
    homeTeam: "Brazil", awayTeam: "Norway",
    homeFormation: "4-3-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Alisson",number:1,position:"GK"},
      {id:2,name:"Danilo Luiz",number:13,position:"RB"},
      {id:3,name:"Marquinhos",number:4,position:"CB"},
      {id:4,name:"Gabriel Magalhães",number:3,position:"CB"},
      {id:5,name:"Douglas Santos",number:16,position:"LB"},
      {id:6,name:"Casemiro",number:5,position:"DM"},
      {id:7,name:"Bruno Guimarães",number:8,position:"CM"},
      {id:8,name:"Lucas Paquetá",number:20,position:"CM"},
      {id:9,name:"Rayan",number:26,position:"RF"},
      {id:10,name:"Endrick",number:19,position:"CF"},
      {id:11,name:"Vinícius Júnior",number:7,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Gabriel Martinelli",number:22,position:"FW"},
      {id:13,name:"Matheus Cunha",number:9,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Ørjan Nyland",number:1,position:"GK"},
      {id:21,name:"Marcus Holmgren Pedersen",number:16,position:"RB"},
      {id:22,name:"Kristoffer Ajer",number:3,position:"CB"},
      {id:23,name:"Torbjørn Heggem",number:17,position:"CB"},
      {id:24,name:"David Møller Wolfe",number:5,position:"LB"},
      {id:25,name:"Patrick Berg",number:6,position:"CM"},
      {id:26,name:"Sander Berge",number:8,position:"CM"},
      {id:27,name:"Martin Ødegaard",number:10,position:"AM"},
      {id:28,name:"Alexander Sørloth",number:7,position:"RF"},
      {id:29,name:"Erling Haaland",number:9,position:"CF"},
      {id:30,name:"Antonio Nusa",number:20,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Oscar Bobb",number:22,position:"MF"},
      {id:32,name:"Andreas Schjelderup",number:21,position:"MF"},
    ],
  },
  "Mexico_England": {
    homeTeam: "Mexico", awayTeam: "England",
    homeFormation: "4-3-3", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Raúl Rangel",number:1,position:"GK"},
      {id:2,name:"Jorge Sánchez",number:2,position:"RB"},
      {id:3,name:"César Montes",number:3,position:"CB"},
      {id:4,name:"Johan Vásquez",number:5,position:"CB"},
      {id:5,name:"Jesús Gallardo",number:23,position:"LB"},
      {id:6,name:"Érik Lira",number:6,position:"DM"},
      {id:7,name:"Brian Gutiérrez",number:26,position:"CM"},
      {id:8,name:"Luis Romo",number:7,position:"CM"},
      {id:9,name:"Roberto Alvarado",number:25,position:"RF"},
      {id:10,name:"Santiago Giménez",number:11,position:"CF"},
      {id:11,name:"Julián Quiñones",number:16,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Raúl Jiménez",number:9,position:"FW"},
      {id:13,name:"Orbelín Pineda",number:17,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Jordan Pickford",number:1,position:"GK"},
      {id:21,name:"Djed Spence",number:25,position:"RB"},
      {id:22,name:"Ezri Konsa",number:2,position:"CB"},
      {id:23,name:"Marc Guéhi",number:6,position:"CB"},
      {id:24,name:"Nico O'Reilly",number:3,position:"LB"},
      {id:25,name:"Elliot Anderson",number:8,position:"CM"},
      {id:26,name:"Declan Rice",number:4,position:"CM"},
      {id:27,name:"Bukayo Saka",number:7,position:"RW"},
      {id:28,name:"Jude Bellingham",number:10,position:"AM"},
      {id:29,name:"Anthony Gordon",number:18,position:"LW"},
      {id:30,name:"Harry Kane",number:9,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Eberechi Eze",number:21,position:"MF"},
      {id:32,name:"Marcus Rashford",number:11,position:"FW"},
    ],
  },
  "Portugal_Spain": {
    homeTeam: "Portugal", awayTeam: "Spain",
    homeFormation: "4-3-3", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Diogo Costa",number:1,position:"GK"},
      {id:2,name:"João Cancelo",number:20,position:"RB"},
      {id:3,name:"Rúben Dias",number:3,position:"CB"},
      {id:4,name:"Renato Veiga",number:13,position:"CB"},
      {id:5,name:"Nuno Mendes",number:25,position:"LB"},
      {id:6,name:"João Neves",number:15,position:"CM"},
      {id:7,name:"Bernardo Silva",number:10,position:"CM"},
      {id:8,name:"Bruno Fernandes",number:8,position:"AM"},
      {id:9,name:"Pedro Neto",number:18,position:"RW"},
      {id:10,name:"Rafael Leão",number:17,position:"LW"},
      {id:11,name:"Cristiano Ronaldo",number:7,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Gonçalo Ramos",number:9,position:"FW"},
      {id:13,name:"Francisco Conceição",number:26,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Unai Simón",number:23,position:"GK"},
      {id:21,name:"Pedro Porro",number:12,position:"RB"},
      {id:22,name:"Pau Cubarsí",number:22,position:"CB"},
      {id:23,name:"Aymeric Laporte",number:14,position:"CB"},
      {id:24,name:"Marc Cucurella",number:24,position:"LB"},
      {id:25,name:"Rodri",number:16,position:"DM"},
      {id:26,name:"Pedri",number:20,position:"CM"},
      {id:27,name:"Dani Olmo",number:10,position:"CM"},
      {id:28,name:"Lamine Yamal",number:19,position:"RF"},
      {id:29,name:"Mikel Oyarzabal",number:21,position:"CF"},
      {id:30,name:"Álex Baena",number:15,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Mikel Merino",number:6,position:"MF"},
      {id:32,name:"Ferran Torres",number:7,position:"FW"},
    ],
  },
  "USA_Belgium": {
    homeTeam: "USA", awayTeam: "Belgium",
    homeFormation: "3-4-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Matt Freese",number:24,position:"GK"},
      {id:2,name:"Alex Freeman",number:16,position:"CB"},
      {id:3,name:"Chris Richards",number:3,position:"CB"},
      {id:4,name:"Tim Ream",number:13,position:"CB"},
      {id:5,name:"Sergiño Dest",number:2,position:"RM"},
      {id:6,name:"Weston McKennie",number:8,position:"CM"},
      {id:7,name:"Tyler Adams",number:4,position:"CM"},
      {id:8,name:"Malik Tillman",number:17,position:"CM"},
      {id:9,name:"Antonee Robinson",number:5,position:"LM"},
      {id:10,name:"Christian Pulisic",number:10,position:"CF"},
      {id:11,name:"Ricardo Pepi",number:9,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Giovanni Reyna",number:7,position:"MF"},
      {id:13,name:"Sebastian Berhalter",number:14,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Thibaut Courtois",number:1,position:"GK"},
      {id:21,name:"Timothy Castagne",number:21,position:"RB"},
      {id:22,name:"Brandon Mechele",number:4,position:"CB"},
      {id:23,name:"Arthur Theate",number:3,position:"CB"},
      {id:24,name:"Maxim De Cuyper",number:5,position:"LB"},
      {id:25,name:"Youri Tielemans",number:8,position:"CM"},
      {id:26,name:"Hans Vanaken",number:20,position:"CM"},
      {id:27,name:"Leandro Trossard",number:10,position:"RW"},
      {id:28,name:"Kevin De Bruyne",number:7,position:"AM"},
      {id:29,name:"Jérémy Doku",number:11,position:"LW"},
      {id:30,name:"Romelu Lukaku",number:9,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Dodi Lukébakio",number:14,position:"FW"},
      {id:32,name:"Charles De Ketelaere",number:17,position:"FW"},
    ],
  },
  "Argentina_Egypt": {
    homeTeam: "Argentina", awayTeam: "Egypt",
    homeFormation: "4-2-3-1", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Emiliano Martínez",number:23,position:"GK"},
      {id:2,name:"Nahuel Molina",number:26,position:"RB"},
      {id:3,name:"Cristian Romero",number:13,position:"CB"},
      {id:4,name:"Lisandro Martínez",number:6,position:"CB"},
      {id:5,name:"Nicolás Tagliafico",number:3,position:"LB"},
      {id:6,name:"Rodrigo De Paul",number:7,position:"RM"},
      {id:7,name:"Alexis Mac Allister",number:20,position:"CM"},
      {id:8,name:"Enzo Fernández",number:24,position:"CM"},
      {id:9,name:"Nico González",number:15,position:"LM"},
      {id:10,name:"Lionel Messi",number:10,position:"CF"},
      {id:11,name:"Lautaro Martínez",number:22,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Julián Alvarez",number:9,position:"FW"},
      {id:13,name:"Leandro Paredes",number:5,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Mostafa Shobeir",number:23,position:"GK"},
      {id:21,name:"Mohamed Hany",number:3,position:"RB"},
      {id:22,name:"Yasser Ibrahim",number:2,position:"CB"},
      {id:23,name:"Ramy Rabia",number:5,position:"CB"},
      {id:24,name:"Karim Hafez",number:15,position:"LB"},
      {id:25,name:"Emam Ashour",number:8,position:"RM"},
      {id:26,name:"Hamdy Fathy",number:14,position:"CM"},
      {id:27,name:"Marwan Attia",number:19,position:"CM"},
      {id:28,name:"Haissem Hassan",number:12,position:"LM"},
      {id:29,name:"Mohamed Salah",number:10,position:"CF"},
      {id:30,name:"Omar Marmoush",number:22,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Mahmoud Saber",number:21,position:"MF"},
      {id:32,name:"Hossam Abdelmaguid",number:4,position:"DF"},
    ],
  },
  "Switzerland_Colombia": {
    homeTeam: "Switzerland", awayTeam: "Colombia",
    homeFormation: "4-2-3-1", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Gregor Kobel",number:1,position:"GK"},
      {id:2,name:"Denis Zakaria",number:6,position:"RB"},
      {id:3,name:"Nico Elvedi",number:4,position:"CB"},
      {id:4,name:"Manuel Akanji",number:5,position:"CB"},
      {id:5,name:"Ricardo Rodriguez",number:13,position:"LB"},
      {id:6,name:"Remo Freuler",number:8,position:"CM"},
      {id:7,name:"Granit Xhaka",number:10,position:"CM"},
      {id:8,name:"Dan Ndoye",number:11,position:"RW"},
      {id:9,name:"Fabian Rieder",number:22,position:"AM"},
      {id:10,name:"Rubén Vargas",number:17,position:"LW"},
      {id:11,name:"Breel Embolo",number:7,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Noah Okafor",number:19,position:"FW"},
      {id:13,name:"Zeki Amdouni",number:23,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Camilo Vargas",number:12,position:"GK"},
      {id:21,name:"Daniel Muñoz",number:2,position:"RB"},
      {id:22,name:"Davinson Sánchez",number:23,position:"CB"},
      {id:23,name:"Jhon Lucumí",number:3,position:"CB"},
      {id:24,name:"Johan Mojica",number:17,position:"LB"},
      {id:25,name:"Jefferson Lerma",number:16,position:"DM"},
      {id:26,name:"Richard Ríos",number:6,position:"CM"},
      {id:27,name:"Gustavo Puerta",number:14,position:"CM"},
      {id:28,name:"James Rodríguez",number:10,position:"RF"},
      {id:29,name:"Luis Díaz",number:7,position:"LF"},
      {id:30,name:"Luis Suárez",number:25,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Jhon Córdoba",number:9,position:"FW"},
      {id:32,name:"Juan Quintero",number:20,position:"MF"},
    ],
  },
'''

old = "export const HARDCODED_LINEUPS: Record<string, MatchLineup> = {"
new = "export const HARDCODED_LINEUPS: Record<string, MatchLineup> = {" + r16_lineups

if old in content:
    content = content.replace(old, new, 1)
    with open('src/services/footballData.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Done')
else:
    print('ERROR: marker not found')
