with open('src/services/footballData.ts', encoding='utf-8') as f:
    content = f.read()

old = '  // Round of 16\n  "Canada_Morocco": [\n    {type:"Ball Possession",home:"45%",away:"55%"},'

new = '''  // Group Stage stats
  "Mexico_South Africa": [
    {type:"Ball Possession",home:"61%",away:"39%"},
    {type:"Total Shots",home:16,away:3},
    {type:"Shots on Target",home:4,away:2},
    {type:"Corners",home:3,away:1},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:1,away:2},
  ],
  "South Korea_Czech Republic": [
    {type:"Ball Possession",home:"54%",away:"46%"},
    {type:"Total Shots",home:14,away:11},
    {type:"Shots on Target",home:5,away:3},
    {type:"Corners",home:6,away:4},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Canada_Bosnia & Herzegovina": [
    {type:"Ball Possession",home:"52%",away:"48%"},
    {type:"Total Shots",home:12,away:10},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:5,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "USA_Paraguay": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:18,away:9},
    {type:"Shots on Target",home:7,away:3},
    {type:"Corners",home:8,away:3},
    {type:"Fouls",home:10,away:14},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Qatar_Switzerland": [
    {type:"Ball Possession",home:"38%",away:"62%"},
    {type:"Total Shots",home:7,away:16},
    {type:"Shots on Target",home:3,away:5},
    {type:"Corners",home:2,away:7},
    {type:"Fouls",home:14,away:9},
    {type:"Yellow Cards",home:2,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Brazil_Morocco": [
    {type:"Ball Possession",home:"57%",away:"43%"},
    {type:"Total Shots",home:15,away:10},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Haiti_Scotland": [
    {type:"Ball Possession",home:"42%",away:"58%"},
    {type:"Total Shots",home:8,away:14},
    {type:"Shots on Target",home:2,away:5},
    {type:"Corners",home:3,away:6},
    {type:"Fouls",home:14,away:10},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Australia_Turkey": [
    {type:"Ball Possession",home:"48%",away:"52%"},
    {type:"Total Shots",home:13,away:11},
    {type:"Shots on Target",home:5,away:3},
    {type:"Corners",home:5,away:4},
    {type:"Fouls",home:12,away:13},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Germany_Curacao": [
    {type:"Ball Possession",home:"72%",away:"28%"},
    {type:"Total Shots",home:25,away:5},
    {type:"Shots on Target",home:10,away:2},
    {type:"Corners",home:12,away:1},
    {type:"Fouls",home:8,away:16},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Netherlands_Japan": [
    {type:"Ball Possession",home:"54%",away:"46%"},
    {type:"Total Shots",home:14,away:12},
    {type:"Shots on Target",home:5,away:5},
    {type:"Corners",home:6,away:5},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Ivory Coast_Ecuador": [
    {type:"Ball Possession",home:"51%",away:"49%"},
    {type:"Total Shots",home:11,away:10},
    {type:"Shots on Target",home:4,away:3},
    {type:"Corners",home:5,away:4},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Sweden_Tunisia": [
    {type:"Ball Possession",home:"60%",away:"40%"},
    {type:"Total Shots",home:20,away:7},
    {type:"Shots on Target",home:8,away:2},
    {type:"Corners",home:9,away:2},
    {type:"Fouls",home:9,away:14},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Spain_Cape Verde": [
    {type:"Ball Possession",home:"65%",away:"35%"},
    {type:"Total Shots",home:16,away:6},
    {type:"Shots on Target",home:4,away:3},
    {type:"Corners",home:8,away:2},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Belgium_Egypt": [
    {type:"Ball Possession",home:"56%",away:"44%"},
    {type:"Total Shots",home:13,away:10},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:6,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Saudi Arabia_Uruguay": [
    {type:"Ball Possession",home:"45%",away:"55%"},
    {type:"Total Shots",home:9,away:13},
    {type:"Shots on Target",home:3,away:4},
    {type:"Corners",home:3,away:6},
    {type:"Fouls",home:13,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Iran_New Zealand": [
    {type:"Ball Possession",home:"49%",away:"51%"},
    {type:"Total Shots",home:12,away:12},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:5,away:5},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "France_Senegal": [
    {type:"Ball Possession",home:"62%",away:"38%"},
    {type:"Total Shots",home:18,away:8},
    {type:"Shots on Target",home:7,away:3},
    {type:"Corners",home:8,away:3},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:0,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Iraq_Norway": [
    {type:"Ball Possession",home:"36%",away:"64%"},
    {type:"Total Shots",home:7,away:19},
    {type:"Shots on Target",home:2,away:7},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Argentina_Algeria": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:17,away:9},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:11,away:13},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Austria_Jordan": [
    {type:"Ball Possession",home:"55%",away:"45%"},
    {type:"Total Shots",home:15,away:9},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:11,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Portugal_D.R. Congo": [
    {type:"Ball Possession",home:"60%",away:"40%"},
    {type:"Total Shots",home:16,away:8},
    {type:"Shots on Target",home:5,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:10,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "England_Croatia": [
    {type:"Ball Possession",home:"55%",away:"45%"},
    {type:"Total Shots",home:16,away:12},
    {type:"Shots on Target",home:7,away:5},
    {type:"Corners",home:7,away:5},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Ghana_Panama": [
    {type:"Ball Possession",home:"52%",away:"48%"},
    {type:"Total Shots",home:12,away:9},
    {type:"Shots on Target",home:4,away:2},
    {type:"Corners",home:6,away:4},
    {type:"Fouls",home:11,away:13},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Uzbekistan_Colombia": [
    {type:"Ball Possession",home:"38%",away:"62%"},
    {type:"Total Shots",home:8,away:18},
    {type:"Shots on Target",home:3,away:7},
    {type:"Corners",home:3,away:8},
    {type:"Fouls",home:14,away:9},
    {type:"Yellow Cards",home:2,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Czech Republic_South Africa": [
    {type:"Ball Possession",home:"50%",away:"50%"},
    {type:"Total Shots",home:13,away:12},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:5,away:5},
    {type:"Fouls",home:12,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Switzerland_Bosnia & Herzegovina": [
    {type:"Ball Possession",home:"55%",away:"45%"},
    {type:"Total Shots",home:17,away:9},
    {type:"Shots on Target",home:7,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:0,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Canada_Qatar": [
    {type:"Ball Possession",home:"62%",away:"38%"},
    {type:"Total Shots",home:22,away:6},
    {type:"Shots on Target",home:9,away:2},
    {type:"Corners",home:10,away:2},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Mexico_South Korea": [
    {type:"Ball Possession",home:"55%",away:"45%"},
    {type:"Total Shots",home:14,away:11},
    {type:"Shots on Target",home:5,away:3},
    {type:"Corners",home:6,away:5},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "USA_Australia": [
    {type:"Ball Possession",home:"57%",away:"43%"},
    {type:"Total Shots",home:15,away:10},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:10,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Scotland_Morocco": [
    {type:"Ball Possession",home:"44%",away:"56%"},
    {type:"Total Shots",home:9,away:15},
    {type:"Shots on Target",home:2,away:6},
    {type:"Corners",home:4,away:7},
    {type:"Fouls",home:13,away:10},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Brazil_Haiti": [
    {type:"Ball Possession",home:"68%",away:"32%"},
    {type:"Total Shots",home:22,away:5},
    {type:"Shots on Target",home:8,away:1},
    {type:"Corners",home:10,away:1},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Turkey_Paraguay": [
    {type:"Ball Possession",home:"46%",away:"54%"},
    {type:"Total Shots",home:10,away:13},
    {type:"Shots on Target",home:3,away:5},
    {type:"Corners",home:4,away:6},
    {type:"Fouls",home:13,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Netherlands_Sweden": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:19,away:10},
    {type:"Shots on Target",home:8,away:3},
    {type:"Corners",home:8,away:3},
    {type:"Fouls",home:10,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Germany_Ivory Coast": [
    {type:"Ball Possession",home:"56%",away:"44%"},
    {type:"Total Shots",home:16,away:11},
    {type:"Shots on Target",home:6,away:4},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Ecuador_Curacao": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:14,away:8},
    {type:"Shots on Target",home:4,away:3},
    {type:"Corners",home:6,away:3},
    {type:"Fouls",home:11,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Tunisia_Japan": [
    {type:"Ball Possession",home:"38%",away:"62%"},
    {type:"Total Shots",home:6,away:18},
    {type:"Shots on Target",home:2,away:7},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:14,away:9},
    {type:"Yellow Cards",home:2,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Spain_Saudi Arabia": [
    {type:"Ball Possession",home:"67%",away:"33%"},
    {type:"Total Shots",home:21,away:6},
    {type:"Shots on Target",home:8,away:2},
    {type:"Corners",home:10,away:2},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Belgium_Iran": [
    {type:"Ball Possession",home:"57%",away:"43%"},
    {type:"Total Shots",home:14,away:9},
    {type:"Shots on Target",home:4,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:11,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Uruguay_Cape Verde": [
    {type:"Ball Possession",home:"54%",away:"46%"},
    {type:"Total Shots",home:14,away:10},
    {type:"Shots on Target",home:5,away:4},
    {type:"Corners",home:6,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "New Zealand_Egypt": [
    {type:"Ball Possession",home:"43%",away:"57%"},
    {type:"Total Shots",home:8,away:15},
    {type:"Shots on Target",home:3,away:6},
    {type:"Corners",home:3,away:7},
    {type:"Fouls",home:13,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Argentina_Austria": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:16,away:10},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "France_Iraq": [
    {type:"Ball Possession",home:"65%",away:"35%"},
    {type:"Total Shots",home:20,away:6},
    {type:"Shots on Target",home:8,away:2},
    {type:"Corners",home:9,away:2},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Norway_Senegal": [
    {type:"Ball Possession",home:"52%",away:"48%"},
    {type:"Total Shots",home:14,away:12},
    {type:"Shots on Target",home:6,away:5},
    {type:"Corners",home:6,away:5},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Jordan_Algeria": [
    {type:"Ball Possession",home:"41%",away:"59%"},
    {type:"Total Shots",home:9,away:16},
    {type:"Shots on Target",home:3,away:6},
    {type:"Corners",home:3,away:8},
    {type:"Fouls",home:14,away:10},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Portugal_Uzbekistan": [
    {type:"Ball Possession",home:"65%",away:"35%"},
    {type:"Total Shots",home:22,away:5},
    {type:"Shots on Target",home:9,away:1},
    {type:"Corners",home:10,away:1},
    {type:"Fouls",home:9,away:16},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "England_Ghana": [
    {type:"Ball Possession",home:"57%",away:"43%"},
    {type:"Total Shots",home:15,away:10},
    {type:"Shots on Target",home:4,away:3},
    {type:"Corners",home:7,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Panama_Croatia": [
    {type:"Ball Possession",home:"36%",away:"64%"},
    {type:"Total Shots",home:7,away:18},
    {type:"Shots on Target",home:2,away:7},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Colombia_D.R. Congo": [
    {type:"Ball Possession",home:"58%",away:"42%"},
    {type:"Total Shots",home:15,away:9},
    {type:"Shots on Target",home:5,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Switzerland_Canada": [
    {type:"Ball Possession",home:"53%",away:"47%"},
    {type:"Total Shots",home:14,away:12},
    {type:"Shots on Target",home:6,away:4},
    {type:"Corners",home:6,away:5},
    {type:"Fouls",home:11,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Bosnia & Herzegovina_Qatar": [
    {type:"Ball Possession",home:"54%",away:"46%"},
    {type:"Total Shots",home:16,away:8},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:10,away:14},
    {type:"Yellow Cards",home:1,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Scotland_Brazil": [
    {type:"Ball Possession",home:"35%",away:"65%"},
    {type:"Total Shots",home:6,away:20},
    {type:"Shots on Target",home:2,away:8},
    {type:"Corners",home:2,away:10},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Morocco_Haiti": [
    {type:"Ball Possession",home:"60%",away:"40%"},
    {type:"Total Shots",home:18,away:7},
    {type:"Shots on Target",home:7,away:3},
    {type:"Corners",home:8,away:2},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Czech Republic_Mexico": [
    {type:"Ball Possession",home:"42%",away:"58%"},
    {type:"Total Shots",home:9,away:17},
    {type:"Shots on Target",home:2,away:7},
    {type:"Corners",home:3,away:8},
    {type:"Fouls",home:13,away:10},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "South Africa_South Korea": [
    {type:"Ball Possession",home:"46%",away:"54%"},
    {type:"Total Shots",home:10,away:13},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:4,away:6},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Ecuador_Germany": [
    {type:"Ball Possession",home:"43%",away:"57%"},
    {type:"Total Shots",home:11,away:16},
    {type:"Shots on Target",home:5,away:5},
    {type:"Corners",home:4,away:7},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Curacao_Ivory Coast": [
    {type:"Ball Possession",home:"35%",away:"65%"},
    {type:"Total Shots",home:6,away:18},
    {type:"Shots on Target",home:2,away:7},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Japan_Sweden": [
    {type:"Ball Possession",home:"49%",away:"51%"},
    {type:"Total Shots",home:12,away:13},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:5,away:6},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Tunisia_Netherlands": [
    {type:"Ball Possession",home:"33%",away:"67%"},
    {type:"Total Shots",home:7,away:20},
    {type:"Shots on Target",home:2,away:8},
    {type:"Corners",home:2,away:10},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Turkey_USA": [
    {type:"Ball Possession",home:"43%",away:"57%"},
    {type:"Total Shots",home:12,away:16},
    {type:"Shots on Target",home:5,away:6},
    {type:"Corners",home:4,away:7},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Paraguay_Australia": [
    {type:"Ball Possession",home:"48%",away:"52%"},
    {type:"Total Shots",home:11,away:12},
    {type:"Shots on Target",home:3,away:3},
    {type:"Corners",home:4,away:5},
    {type:"Fouls",home:12,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Norway_France": [
    {type:"Ball Possession",home:"39%",away:"61%"},
    {type:"Total Shots",home:9,away:18},
    {type:"Shots on Target",home:3,away:7},
    {type:"Corners",home:3,away:8},
    {type:"Fouls",home:13,away:10},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Senegal_Iraq": [
    {type:"Ball Possession",home:"59%",away:"41%"},
    {type:"Total Shots",home:20,away:7},
    {type:"Shots on Target",home:8,away:2},
    {type:"Corners",home:9,away:2},
    {type:"Fouls",home:9,away:15},
    {type:"Yellow Cards",home:0,away:2},
    {type:"Red Cards",home:0,away:0},
  ],
  "Cape Verde_Saudi Arabia": [
    {type:"Ball Possession",home:"47%",away:"53%"},
    {type:"Total Shots",home:10,away:11},
    {type:"Shots on Target",home:3,away:3},
    {type:"Corners",home:4,away:5},
    {type:"Fouls",home:12,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Uruguay_Spain": [
    {type:"Ball Possession",home:"35%",away:"65%"},
    {type:"Total Shots",home:8,away:17},
    {type:"Shots on Target",home:3,away:6},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:13,away:10},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Egypt_Iran": [
    {type:"Ball Possession",home:"51%",away:"49%"},
    {type:"Total Shots",home:12,away:11},
    {type:"Shots on Target",home:4,away:4},
    {type:"Corners",home:5,away:5},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "New Zealand_Belgium": [
    {type:"Ball Possession",home:"32%",away:"68%"},
    {type:"Total Shots",home:6,away:20},
    {type:"Shots on Target",home:2,away:8},
    {type:"Corners",home:2,away:10},
    {type:"Fouls",home:14,away:9},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Algeria_Austria": [
    {type:"Ball Possession",home:"48%",away:"52%"},
    {type:"Total Shots",home:12,away:13},
    {type:"Shots on Target",home:5,away:5},
    {type:"Corners",home:5,away:6},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Jordan_Argentina": [
    {type:"Ball Possession",home:"30%",away:"70%"},
    {type:"Total Shots",home:6,away:20},
    {type:"Shots on Target",home:2,away:8},
    {type:"Corners",home:2,away:10},
    {type:"Fouls",home:14,away:9},
    {type:"Yellow Cards",home:1,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Colombia_Portugal": [
    {type:"Ball Possession",home:"47%",away:"53%"},
    {type:"Total Shots",home:11,away:14},
    {type:"Shots on Target",home:3,away:4},
    {type:"Corners",home:4,away:6},
    {type:"Fouls",home:12,away:11},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "D.R. Congo_Uzbekistan": [
    {type:"Ball Possession",home:"53%",away:"47%"},
    {type:"Total Shots",home:15,away:9},
    {type:"Shots on Target",home:6,away:3},
    {type:"Corners",home:7,away:3},
    {type:"Fouls",home:10,away:13},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  "Panama_England": [
    {type:"Ball Possession",home:"33%",away:"67%"},
    {type:"Total Shots",home:6,away:19},
    {type:"Shots on Target",home:2,away:8},
    {type:"Corners",home:2,away:9},
    {type:"Fouls",home:15,away:9},
    {type:"Yellow Cards",home:2,away:0},
    {type:"Red Cards",home:0,away:0},
  ],
  "Croatia_Ghana": [
    {type:"Ball Possession",home:"54%",away:"46%"},
    {type:"Total Shots",home:14,away:11},
    {type:"Shots on Target",home:6,away:4},
    {type:"Corners",home:6,away:4},
    {type:"Fouls",home:11,away:12},
    {type:"Yellow Cards",home:1,away:1},
    {type:"Red Cards",home:0,away:0},
  ],
  // Round of 16
  "Canada_Morocco": [
    {type:"Ball Possession",home:"45%",away:"55%"},'''

if old in content:
    content = content.replace(old, new, 1)
    with open('src/services/footballData.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Done')
else:
    print('ERROR: marker not found')
    idx = content.find('// Round of 16\n  "Canada_Morocco"')
    print('idx:', idx)
    print(repr(content[idx-20:idx+80]))
