with open('src/services/footballData.ts', encoding='utf-8') as f:
    content = f.read()

hardcoded_lineups = '''
export const HARDCODED_LINEUPS: Record<string, MatchLineup> = {
  "South Africa_Canada": {
    homeTeam: "South Africa", awayTeam: "Canada",
    homeFormation: "4-3-3", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Ronwen Williams",number:1,position:"GK"},
      {id:2,name:"Khuliso Mudau",number:20,position:"RB"},
      {id:3,name:"Ime Okon",number:21,position:"CB"},
      {id:4,name:"Mbekezeli Mbokazi",number:14,position:"CB"},
      {id:5,name:"Aubrey Modiba",number:6,position:"LB"},
      {id:6,name:"Sphephelo Sithole",number:13,position:"CM"},
      {id:7,name:"Teboho Mokoena",number:4,position:"CM"},
      {id:8,name:"Thapelo Maseko",number:12,position:"RW"},
      {id:9,name:"Relebohile Mofokeng",number:10,position:"AM"},
      {id:10,name:"Oswin Appollis",number:7,position:"LW"},
      {id:11,name:"Evidence Makgopa",number:17,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Thalente Mbatha",number:5,position:"MF"},
      {id:13,name:"Iqraam Rayners",number:15,position:"FW"},
      {id:14,name:"Tshepang Moremi",number:8,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Maxime Crépeau",number:16,position:"GK"},
      {id:21,name:"Alistair Johnston",number:2,position:"RB"},
      {id:22,name:"Moïse Bombito",number:15,position:"CB"},
      {id:23,name:"Derek Cornelius",number:13,position:"CB"},
      {id:24,name:"Richie Laryea",number:22,position:"LB"},
      {id:25,name:"Tajon Buchanan",number:17,position:"RM"},
      {id:26,name:"Nathan Saliba",number:25,position:"CM"},
      {id:27,name:"Stephen Eustáquio",number:7,position:"CM"},
      {id:28,name:"Liam Millar",number:11,position:"LM"},
      {id:29,name:"Jonathan David",number:10,position:"CF"},
      {id:30,name:"Tani Oluwaseyi",number:12,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Niko Sigur",number:23,position:"DF"},
      {id:32,name:"Luc de Fougerolles",number:4,position:"DF"},
      {id:33,name:"Promise David",number:24,position:"FW"},
      {id:34,name:"Jacob Shaffelburg",number:14,position:"MF"},
      {id:35,name:"Alphonso Davies",number:19,position:"DF"},
    ],
  },
  "Brazil_Japan": {
    homeTeam: "Brazil", awayTeam: "Japan",
    homeFormation: "4-3-3", awayFormation: "3-4-3",
    homeStartXI: [
      {id:1,name:"Alisson",number:1,position:"GK"},
      {id:2,name:"Danilo Luiz",number:13,position:"RB"},
      {id:3,name:"Marquinhos",number:4,position:"CB"},
      {id:4,name:"Gabriel Magalhães",number:3,position:"CB"},
      {id:5,name:"Douglas Santos",number:16,position:"LB"},
      {id:6,name:"Casemiro",number:5,position:"DM"},
      {id:7,name:"Bruno Guimarães",number:8,position:"CM"},
      {id:8,name:"Lucas Paquetá",number:20,position:"CM"},
      {id:9,name:"Rayan",number:26,position:"RF"},
      {id:10,name:"Matheus Cunha",number:9,position:"CF"},
      {id:11,name:"Vinícius Júnior",number:7,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Endrick",number:19,position:"FW"},
      {id:13,name:"Gabriel Martinelli",number:22,position:"FW"},
      {id:14,name:"Fabinho",number:17,position:"MF"},
      {id:15,name:"Danilo Santos",number:18,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Zion Suzuki",number:1,position:"GK"},
      {id:21,name:"Takehiro Tomiyasu",number:22,position:"CB"},
      {id:22,name:"Shōgo Taniguchi",number:3,position:"CB"},
      {id:23,name:"Hiroki Itō",number:21,position:"CB"},
      {id:24,name:"Ritsu Dōan",number:10,position:"RM"},
      {id:25,name:"Kaishū Sano",number:24,position:"CM"},
      {id:26,name:"Daichi Kamada",number:15,position:"CM"},
      {id:27,name:"Keito Nakamura",number:13,position:"LM"},
      {id:28,name:"Junya Itō",number:14,position:"RF"},
      {id:29,name:"Ayase Ueda",number:18,position:"CF"},
      {id:30,name:"Daizen Maeda",number:11,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Junnosuke Suzuki",number:25,position:"DF"},
      {id:32,name:"Yukinari Sugawara",number:2,position:"DF"},
      {id:33,name:"Ao Tanaka",number:7,position:"MF"},
      {id:34,name:"Shūto Machino",number:6,position:"FW"},
      {id:35,name:"Kōki Ogawa",number:19,position:"FW"},
    ],
  },
  "Germany_Paraguay": {
    homeTeam: "Germany", awayTeam: "Paraguay",
    homeFormation: "4-2-3-1", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Manuel Neuer",number:1,position:"GK"},
      {id:2,name:"Joshua Kimmich",number:6,position:"RB"},
      {id:3,name:"Jonathan Tah",number:4,position:"CB"},
      {id:4,name:"Antonio Rüdiger",number:2,position:"CB"},
      {id:5,name:"Nathaniel Brown",number:18,position:"LB"},
      {id:6,name:"Felix Nmecha",number:23,position:"CM"},
      {id:7,name:"Aleksandar Pavlović",number:5,position:"CM"},
      {id:8,name:"Leroy Sané",number:19,position:"RW"},
      {id:9,name:"Kai Havertz",number:7,position:"AM"},
      {id:10,name:"Florian Wirtz",number:17,position:"LW"},
      {id:11,name:"Deniz Undav",number:26,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Leon Goretzka",number:8,position:"MF"},
      {id:13,name:"Jamal Musiala",number:10,position:"MF"},
      {id:14,name:"Waldemar Anton",number:3,position:"DF"},
      {id:15,name:"Nick Woltemade",number:11,position:"FW"},
      {id:16,name:"Nadiem Amiri",number:20,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Orlando Gill",number:12,position:"GK"},
      {id:21,name:"Juan José Cáceres",number:4,position:"RB"},
      {id:22,name:"Gustavo Gómez",number:15,position:"CB"},
      {id:23,name:"José Canale",number:13,position:"CB"},
      {id:24,name:"Júnior Alonso",number:6,position:"LB"},
      {id:25,name:"Miguel Almirón",number:10,position:"RM"},
      {id:26,name:"Damián Bobadilla",number:16,position:"CM"},
      {id:27,name:"Andrés Cubas",number:14,position:"CM"},
      {id:28,name:"Matías Galarza",number:23,position:"LM"},
      {id:29,name:"Gabriel Ávalos",number:21,position:"CF"},
      {id:30,name:"Julio Enciso",number:19,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Gustavo Caballero",number:24,position:"MF"},
      {id:32,name:"Maurício",number:11,position:"MF"},
      {id:33,name:"Gustavo Velázquez",number:2,position:"DF"},
      {id:34,name:"Antonio Sanabria",number:9,position:"FW"},
      {id:35,name:"Fabián Balbuena",number:5,position:"DF"},
    ],
  },
  "Netherlands_Morocco": {
    homeTeam: "Netherlands", awayTeam: "Morocco",
    homeFormation: "3-4-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Bart Verbruggen",number:1,position:"GK"},
      {id:2,name:"Jan Paul van Hecke",number:6,position:"CB"},
      {id:3,name:"Virgil van Dijk",number:4,position:"CB"},
      {id:4,name:"Nathan Aké",number:5,position:"CB"},
      {id:5,name:"Denzel Dumfries",number:22,position:"RM"},
      {id:6,name:"Ryan Gravenberch",number:8,position:"CM"},
      {id:7,name:"Frenkie de Jong",number:21,position:"CM"},
      {id:8,name:"Micky van de Ven",number:15,position:"LM"},
      {id:9,name:"Crysencio Summerville",number:24,position:"RF"},
      {id:10,name:"Brian Brobbey",number:19,position:"CF"},
      {id:11,name:"Cody Gakpo",number:11,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Teun Koopmeiners",number:20,position:"MF"},
      {id:13,name:"Wout Weghorst",number:9,position:"FW"},
      {id:14,name:"Quinten Timber",number:26,position:"MF"},
      {id:15,name:"Jorrel Hato",number:25,position:"DF"},
      {id:16,name:"Justin Kluivert",number:7,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Yassine Bounou",number:1,position:"GK"},
      {id:21,name:"Achraf Hakimi",number:2,position:"RB"},
      {id:22,name:"Issa Diop",number:14,position:"CB"},
      {id:23,name:"Chadi Riad",number:18,position:"CB"},
      {id:24,name:"Noussair Mazraoui",number:3,position:"LB"},
      {id:25,name:"Ayyoub Bouaddi",number:6,position:"CM"},
      {id:26,name:"Neil El Aynaoui",number:24,position:"CM"},
      {id:27,name:"Brahim Díaz",number:10,position:"RW"},
      {id:28,name:"Azzedine Ounahi",number:8,position:"AM"},
      {id:29,name:"Bilal El Khannouss",number:23,position:"LW"},
      {id:30,name:"Ismael Saibari",number:11,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Soufiane Rahimi",number:9,position:"FW"},
      {id:32,name:"Chemsdine Talbi",number:7,position:"MF"},
      {id:33,name:"Samir El Mourabet",number:15,position:"MF"},
    ],
  },
  "Ivory Coast_Norway": {
    homeTeam: "Ivory Coast", awayTeam: "Norway",
    homeFormation: "4-3-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Yahia Fofana",number:1,position:"GK"},
      {id:2,name:"Guéla Doué",number:17,position:"RB"},
      {id:3,name:"Odilon Kossounou",number:7,position:"CB"},
      {id:4,name:"Emmanuel Agbadou",number:20,position:"CB"},
      {id:5,name:"Ghislain Konan",number:3,position:"LB"},
      {id:6,name:"Ibrahim Sangaré",number:18,position:"DM"},
      {id:7,name:"Franck Kessié",number:8,position:"CM"},
      {id:8,name:"Christ Inao Oulaï",number:26,position:"CM"},
      {id:9,name:"Nicolas Pépé",number:19,position:"RF"},
      {id:10,name:"Ange-Yoan Bonny",number:9,position:"CF"},
      {id:11,name:"Yan Diomande",number:11,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Amad Diallo",number:15,position:"FW"},
      {id:13,name:"Elye Wahi",number:12,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Ørjan Nyland",number:1,position:"GK"},
      {id:21,name:"Marcus Holmgren Pedersen",number:16,position:"RB"},
      {id:22,name:"Kristoffer Ajer",number:3,position:"CB"},
      {id:23,name:"Torbjørn Heggem",number:17,position:"CB"},
      {id:24,name:"David Møller Wolfe",number:5,position:"LB"},
      {id:25,name:"Patrick Berg",number:6,position:"CM"},
      {id:26,name:"Sander Berge",number:8,position:"CM"},
      {id:27,name:"Martin Ødegaard",number:10,position:"AM"},
      {id:28,name:"Alexander Sørloth",number:7,position:"RF"},
      {id:29,name:"Erling Haaland",number:9,position:"CF"},
      {id:30,name:"Antonio Nusa",number:20,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Andreas Schjelderup",number:21,position:"MF"},
      {id:32,name:"Oscar Bobb",number:22,position:"MF"},
      {id:33,name:"Fredrik Aursnes",number:14,position:"MF"},
    ],
  },
  "France_Sweden": {
    homeTeam: "France", awayTeam: "Sweden",
    homeFormation: "4-2-3-1", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Mike Maignan",number:16,position:"GK"},
      {id:2,name:"Jules Koundé",number:5,position:"RB"},
      {id:3,name:"Dayot Upamecano",number:4,position:"CB"},
      {id:4,name:"William Saliba",number:17,position:"CB"},
      {id:5,name:"Lucas Digne",number:3,position:"LB"},
      {id:6,name:"Aurélien Tchouaméni",number:8,position:"CM"},
      {id:7,name:"Adrien Rabiot",number:14,position:"CM"},
      {id:8,name:"Ousmane Dembélé",number:7,position:"RW"},
      {id:9,name:"Michael Olise",number:11,position:"AM"},
      {id:10,name:"Bradley Barcola",number:12,position:"LW"},
      {id:11,name:"Kylian Mbappé",number:10,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Désiré Doué",number:20,position:"FW"},
      {id:13,name:"Malo Gusto",number:2,position:"DF"},
      {id:14,name:"Théo Hernandez",number:19,position:"DF"},
      {id:15,name:"Jean-Philippe Mateta",number:22,position:"FW"},
      {id:16,name:"Rayan Cherki",number:24,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Jacob Widell Zetterström",number:1,position:"GK"},
      {id:21,name:"Daniel Svensson",number:8,position:"RB"},
      {id:22,name:"Gustaf Lagerbielke",number:2,position:"CB"},
      {id:23,name:"Victor Lindelöf",number:3,position:"CB"},
      {id:24,name:"Gabriel Gudmundsson",number:5,position:"LB"},
      {id:25,name:"Anthony Elanga",number:11,position:"RM"},
      {id:26,name:"Lucas Bergvall",number:7,position:"CM"},
      {id:27,name:"Yasin Ayari",number:18,position:"CM"},
      {id:28,name:"Elliot Stroud",number:24,position:"LM"},
      {id:29,name:"Viktor Gyökeres",number:17,position:"CF"},
      {id:30,name:"Alexander Isak",number:9,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Taha Ali",number:26,position:"FW"},
      {id:32,name:"Besfort Zeneli",number:22,position:"MF"},
      {id:33,name:"Benjamin Nygren",number:10,position:"MF"},
    ],
  },
  "Mexico_Ecuador": {
    homeTeam: "Mexico", awayTeam: "Ecuador",
    homeFormation: "4-3-3", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Raúl Rangel",number:1,position:"GK"},
      {id:2,name:"Jorge Sánchez",number:2,position:"RB"},
      {id:3,name:"César Montes",number:3,position:"CB"},
      {id:4,name:"Johan Vásquez",number:5,position:"CB"},
      {id:5,name:"Jesús Gallardo",number:23,position:"LB"},
      {id:6,name:"Érik Lira",number:6,position:"DM"},
      {id:7,name:"Gilberto Mora",number:19,position:"CM"},
      {id:8,name:"Luis Romo",number:7,position:"CM"},
      {id:9,name:"Roberto Alvarado",number:25,position:"RF"},
      {id:10,name:"Raúl Jiménez",number:9,position:"CF"},
      {id:11,name:"Julián Quiñones",number:16,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Brian Gutiérrez",number:26,position:"MF"},
      {id:13,name:"Obed Vargas",number:18,position:"MF"},
      {id:14,name:"Santiago Giménez",number:11,position:"FW"},
      {id:15,name:"Israel Reyes",number:15,position:"DF"},
      {id:16,name:"Orbelín Pineda",number:17,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Hernán Galíndez",number:1,position:"GK"},
      {id:21,name:"Alan Franco",number:21,position:"RB"},
      {id:22,name:"Joel Ordóñez",number:4,position:"CB"},
      {id:23,name:"Willian Pacho",number:6,position:"CB"},
      {id:24,name:"Piero Hincapié",number:3,position:"LB"},
      {id:25,name:"John Yeboah",number:9,position:"RM"},
      {id:26,name:"Moisés Caicedo",number:23,position:"CM"},
      {id:27,name:"Pedro Vite",number:15,position:"CM"},
      {id:28,name:"Nilson Angulo",number:20,position:"LM"},
      {id:29,name:"Gonzalo Plata",number:19,position:"CF"},
      {id:30,name:"Enner Valencia",number:13,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Yaimar Medina",number:26,position:"MF"},
      {id:32,name:"Ángelo Preciado",number:17,position:"DF"},
      {id:33,name:"Kevin Rodríguez",number:11,position:"FW"},
      {id:34,name:"Kendry Páez",number:10,position:"MF"},
    ],
  },
  "England_D.R. Congo": {
    homeTeam: "England", awayTeam: "D.R. Congo",
    homeFormation: "4-3-3", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Jordan Pickford",number:1,position:"GK"},
      {id:2,name:"Djed Spence",number:25,position:"RB"},
      {id:3,name:"Ezri Konsa",number:2,position:"CB"},
      {id:4,name:"Marc Guéhi",number:6,position:"CB"},
      {id:5,name:"Nico O'Reilly",number:3,position:"LB"},
      {id:6,name:"Elliot Anderson",number:8,position:"CM"},
      {id:7,name:"Declan Rice",number:4,position:"CM"},
      {id:8,name:"Noni Madueke",number:20,position:"RW"},
      {id:9,name:"Jude Bellingham",number:10,position:"AM"},
      {id:10,name:"Marcus Rashford",number:11,position:"LW"},
      {id:11,name:"Harry Kane",number:9,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Bukayo Saka",number:7,position:"FW"},
      {id:13,name:"Anthony Gordon",number:18,position:"FW"},
      {id:14,name:"Eberechi Eze",number:21,position:"MF"},
      {id:15,name:"John Stones",number:5,position:"DF"},
    ],
    awayStartXI: [
      {id:20,name:"Lionel Mpasi",number:1,position:"GK"},
      {id:21,name:"Aaron Wan-Bissaka",number:2,position:"RB"},
      {id:22,name:"Chancel Mbemba",number:22,position:"CB"},
      {id:23,name:"Axel Tuanzebe",number:4,position:"CB"},
      {id:24,name:"Arthur Masuaku",number:26,position:"LB"},
      {id:25,name:"Samuel Moutoussamy",number:8,position:"DM"},
      {id:26,name:"Nathanaël Mbuku",number:7,position:"RM"},
      {id:27,name:"Ngal\'ayel Mukau",number:6,position:"CM"},
      {id:28,name:"Noah Sadiki",number:14,position:"CM"},
      {id:29,name:"Brian Cipenga",number:9,position:"LM"},
      {id:30,name:"Yoane Wissa",number:20,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Meschak Elia",number:13,position:"FW"},
      {id:32,name:"Théo Bongonda",number:10,position:"MF"},
      {id:33,name:"Edo Kayembe",number:25,position:"MF"},
    ],
  },
  "Belgium_Senegal": {
    homeTeam: "Belgium", awayTeam: "Senegal",
    homeFormation: "4-2-3-1", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Thibaut Courtois",number:1,position:"GK"},
      {id:2,name:"Timothy Castagne",number:21,position:"RB"},
      {id:3,name:"Brandon Mechele",number:4,position:"CB"},
      {id:4,name:"Arthur Theate",number:3,position:"CB"},
      {id:5,name:"Maxim De Cuyper",number:5,position:"LB"},
      {id:6,name:"Hans Vanaken",number:20,position:"CM"},
      {id:7,name:"Youri Tielemans",number:8,position:"CM"},
      {id:8,name:"Leandro Trossard",number:10,position:"RW"},
      {id:9,name:"Kevin De Bruyne",number:7,position:"AM"},
      {id:10,name:"Jérémy Doku",number:11,position:"LW"},
      {id:11,name:"Charles De Ketelaere",number:17,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Romelu Lukaku",number:9,position:"FW"},
      {id:13,name:"Dodi Lukébakio",number:14,position:"FW"},
      {id:14,name:"Nicolas Raskin",number:23,position:"MF"},
      {id:15,name:"Thomas Meunier",number:15,position:"DF"},
    ],
    awayStartXI: [
      {id:20,name:"Mory Diaw",number:23,position:"GK"},
      {id:21,name:"Krépin Diatta",number:15,position:"RB"},
      {id:22,name:"Pathé Ciss",number:6,position:"CB"},
      {id:23,name:"Moussa Niakhaté",number:19,position:"CB"},
      {id:24,name:"Ismail Jakobs",number:14,position:"LB"},
      {id:25,name:"Habib Diarra",number:21,position:"CM"},
      {id:26,name:"Idrissa Gueye",number:5,position:"CM"},
      {id:27,name:"Pape Gueye",number:26,position:"CM"},
      {id:28,name:"Iliman Ndiaye",number:13,position:"RF"},
      {id:29,name:"Ismaïla Sarr",number:18,position:"CF"},
      {id:30,name:"Sadio Mané",number:10,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Lamine Camara",number:8,position:"MF"},
      {id:32,name:"Pape Matar Sarr",number:17,position:"MF"},
      {id:33,name:"Nicolas Jackson",number:11,position:"FW"},
    ],
  },
  "USA_Bosnia & Herzegovina": {
    homeTeam: "USA", awayTeam: "Bosnia & Herzegovina",
    homeFormation: "3-4-3", awayFormation: "4-4-2",
    homeStartXI: [
      {id:1,name:"Matt Freese",number:24,position:"GK"},
      {id:2,name:"Alex Freeman",number:16,position:"CB"},
      {id:3,name:"Chris Richards",number:3,position:"CB"},
      {id:4,name:"Tim Ream",number:13,position:"CB"},
      {id:5,name:"Sergiño Dest",number:2,position:"RM"},
      {id:6,name:"Weston McKennie",number:8,position:"CM"},
      {id:7,name:"Tyler Adams",number:4,position:"CM"},
      {id:8,name:"Malik Tillman",number:17,position:"CM"},
      {id:9,name:"Antonee Robinson",number:5,position:"LM"},
      {id:10,name:"Christian Pulisic",number:10,position:"CF"},
      {id:11,name:"Folarin Balogun",number:20,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Sebastian Berhalter",number:14,position:"MF"},
      {id:13,name:"Ricardo Pepi",number:9,position:"FW"},
      {id:14,name:"Giovanni Reyna",number:7,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Nikola Vasilj",number:1,position:"GK"},
      {id:21,name:"Amar Dedić",number:7,position:"RB"},
      {id:22,name:"Nikola Katić",number:18,position:"CB"},
      {id:23,name:"Tarik Muharemović",number:4,position:"CB"},
      {id:24,name:"Stjepan Radeljić",number:21,position:"LB"},
      {id:25,name:"Armin Gigović",number:8,position:"RM"},
      {id:26,name:"Ivan Šunjić",number:14,position:"CM"},
      {id:27,name:"Kerim Alajbegović",number:19,position:"CM"},
      {id:28,name:"Sead Kolašinac",number:5,position:"LM"},
      {id:29,name:"Ermedin Demirović",number:10,position:"CF"},
      {id:30,name:"Edin Džeko",number:11,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Ermin Mahmić",number:26,position:"MF"},
      {id:32,name:"Benjamin Tahirović",number:6,position:"MF"},
      {id:33,name:"Haris Tabaković",number:23,position:"FW"},
    ],
  },
  "Spain_Austria": {
    homeTeam: "Spain", awayTeam: "Austria",
    homeFormation: "4-3-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Unai Simón",number:23,position:"GK"},
      {id:2,name:"Pedro Porro",number:12,position:"RB"},
      {id:3,name:"Pau Cubarsí",number:22,position:"CB"},
      {id:4,name:"Aymeric Laporte",number:14,position:"CB"},
      {id:5,name:"Marc Cucurella",number:24,position:"LB"},
      {id:6,name:"Rodri",number:16,position:"DM"},
      {id:7,name:"Dani Olmo",number:10,position:"CM"},
      {id:8,name:"Pedri",number:20,position:"CM"},
      {id:9,name:"Lamine Yamal",number:19,position:"RF"},
      {id:10,name:"Mikel Oyarzabal",number:21,position:"CF"},
      {id:11,name:"Álex Baena",number:15,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Ferran Torres",number:7,position:"FW"},
      {id:13,name:"Mikel Merino",number:6,position:"MF"},
      {id:14,name:"Gavi",number:9,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Alexander Schlager",number:1,position:"GK"},
      {id:21,name:"Stefan Posch",number:5,position:"RB"},
      {id:22,name:"Kevin Danso",number:3,position:"CB"},
      {id:23,name:"David Alaba",number:8,position:"CB"},
      {id:24,name:"Konrad Laimer",number:20,position:"LB"},
      {id:25,name:"Nicolas Seiwald",number:6,position:"CM"},
      {id:26,name:"Xaver Schlager",number:4,position:"CM"},
      {id:27,name:"Romano Schmid",number:18,position:"RW"},
      {id:28,name:"Paul Wanner",number:24,position:"AM"},
      {id:29,name:"Marcel Sabitzer",number:9,position:"LW"},
      {id:30,name:"Michael Gregoritsch",number:11,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Florian Grillitsch",number:10,position:"MF"},
      {id:32,name:"Carney Chukwuemeka",number:17,position:"MF"},
      {id:33,name:"Marko Arnautović",number:7,position:"FW"},
      {id:34,name:"Saša Kalajdžić",number:14,position:"FW"},
    ],
  },
  "Portugal_Croatia": {
    homeTeam: "Portugal", awayTeam: "Croatia",
    homeFormation: "4-3-3", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Diogo Costa",number:1,position:"GK"},
      {id:2,name:"João Cancelo",number:20,position:"RB"},
      {id:3,name:"Rúben Dias",number:3,position:"CB"},
      {id:4,name:"Renato Veiga",number:13,position:"CB"},
      {id:5,name:"Nuno Mendes",number:25,position:"LB"},
      {id:6,name:"João Neves",number:15,position:"CM"},
      {id:7,name:"Vitinha",number:23,position:"CM"},
      {id:8,name:"Pedro Neto",number:18,position:"RW"},
      {id:9,name:"Bruno Fernandes",number:8,position:"AM"},
      {id:10,name:"Rafael Leão",number:17,position:"LW"},
      {id:11,name:"Cristiano Ronaldo",number:7,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Bernardo Silva",number:10,position:"MF"},
      {id:13,name:"Nélson Semedo",number:2,position:"DF"},
      {id:14,name:"Francisco Conceição",number:26,position:"FW"},
      {id:15,name:"Gonçalo Ramos",number:9,position:"FW"},
      {id:16,name:"Rúben Neves",number:21,position:"MF"},
    ],
    awayStartXI: [
      {id:20,name:"Dominik Livaković",number:1,position:"GK"},
      {id:21,name:"Josip Stanišić",number:2,position:"RB"},
      {id:22,name:"Josip Šutalo",number:6,position:"CB"},
      {id:23,name:"Marin Pongračić",number:3,position:"CB"},
      {id:24,name:"Ivan Perišić",number:14,position:"LB"},
      {id:25,name:"Luka Modrić",number:10,position:"CM"},
      {id:26,name:"Mateo Kovačić",number:8,position:"CM"},
      {id:27,name:"Nikola Vlašić",number:13,position:"RW"},
      {id:28,name:"Petar Sučić",number:17,position:"AM"},
      {id:29,name:"Martin Baturina",number:16,position:"LW"},
      {id:30,name:"Ante Budimir",number:11,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Igor Matanović",number:20,position:"FW"},
      {id:32,name:"Mario Pašalić",number:15,position:"MF"},
      {id:33,name:"Joško Gvardiol",number:4,position:"DF"},
      {id:34,name:"Andrej Kramarić",number:9,position:"FW"},
    ],
  },
  "Switzerland_Algeria": {
    homeTeam: "Switzerland", awayTeam: "Algeria",
    homeFormation: "4-2-3-1", awayFormation: "4-3-3",
    homeStartXI: [
      {id:1,name:"Gregor Kobel",number:1,position:"GK"},
      {id:2,name:"Denis Zakaria",number:6,position:"RB"},
      {id:3,name:"Nico Elvedi",number:4,position:"CB"},
      {id:4,name:"Manuel Akanji",number:5,position:"CB"},
      {id:5,name:"Ricardo Rodriguez",number:13,position:"LB"},
      {id:6,name:"Remo Freuler",number:8,position:"CM"},
      {id:7,name:"Granit Xhaka",number:10,position:"CM"},
      {id:8,name:"Dan Ndoye",number:11,position:"RW"},
      {id:9,name:"Johan Manzambi",number:9,position:"AM"},
      {id:10,name:"Rubén Vargas",number:17,position:"LW"},
      {id:11,name:"Breel Embolo",number:7,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Fabian Rieder",number:22,position:"MF"},
      {id:13,name:"Noah Okafor",number:19,position:"FW"},
      {id:14,name:"Zeki Amdouni",number:23,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Luca Zidane",number:23,position:"GK"},
      {id:21,name:"Rafik Belghali",number:17,position:"RB"},
      {id:22,name:"Aïssa Mandi",number:2,position:"CB"},
      {id:23,name:"Ramy Bensebaini",number:21,position:"CB"},
      {id:24,name:"Rayan Aït-Nouri",number:15,position:"LB"},
      {id:25,name:"Nabil Bentaleb",number:19,position:"DM"},
      {id:26,name:"Ramiz Zerrouki",number:6,position:"CM"},
      {id:27,name:"Farès Chaïbi",number:10,position:"CM"},
      {id:28,name:"Riyad Mahrez",number:7,position:"RF"},
      {id:29,name:"Ibrahim Maza",number:22,position:"CF"},
      {id:30,name:"Houssem Aouar",number:8,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Amine Gouiri",number:9,position:"FW"},
      {id:32,name:"Anis Hadj Moussa",number:11,position:"FW"},
      {id:33,name:"Hicham Boudaoui",number:14,position:"MF"},
    ],
  },
  "Australia_Egypt": {
    homeTeam: "Australia", awayTeam: "Egypt",
    homeFormation: "3-4-3", awayFormation: "4-2-3-1",
    homeStartXI: [
      {id:1,name:"Patrick Beach",number:18,position:"GK"},
      {id:2,name:"Alessandro Circati",number:3,position:"CB"},
      {id:3,name:"Harry Souttar",number:19,position:"CB"},
      {id:4,name:"Lucas Herrington",number:25,position:"CB"},
      {id:5,name:"Jordan Bos",number:5,position:"RM"},
      {id:6,name:"Jackson Irvine",number:22,position:"CM"},
      {id:7,name:"Aiden O\'Neill",number:13,position:"CM"},
      {id:8,name:"Aziz Behich",number:16,position:"LM"},
      {id:9,name:"Cristian Volpato",number:20,position:"RF"},
      {id:10,name:"Nestory Irankunda",number:17,position:"CF"},
      {id:11,name:"Connor Metcalfe",number:8,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Ajdin Hrustic",number:10,position:"FW"},
      {id:13,name:"Mohamed Touré",number:9,position:"FW"},
      {id:14,name:"Awer Mabil",number:11,position:"FW"},
      {id:15,name:"Mathew Ryan",number:1,position:"GK"},
    ],
    awayStartXI: [
      {id:20,name:"Mostafa Shobeir",number:23,position:"GK"},
      {id:21,name:"Mohamed Hany",number:3,position:"RB"},
      {id:22,name:"Yasser Ibrahim",number:2,position:"CB"},
      {id:23,name:"Ramy Rabia",number:5,position:"CB"},
      {id:24,name:"Karim Hafez",number:15,position:"LB"},
      {id:25,name:"Emam Ashour",number:8,position:"RM"},
      {id:26,name:"Hamdy Fathy",number:14,position:"CM"},
      {id:27,name:"Marwan Attia",number:19,position:"CM"},
      {id:28,name:"Mostafa Ziko",number:11,position:"LM"},
      {id:29,name:"Mohamed Salah",number:10,position:"CF"},
      {id:30,name:"Omar Marmoush",number:22,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Haissem Hassan",number:12,position:"FW"},
      {id:32,name:"Hossam Abdelmaguid",number:4,position:"DF"},
      {id:33,name:"Mahmoud Saber",number:21,position:"MF"},
    ],
  },
  "Argentina_Cape Verde": {
    homeTeam: "Argentina", awayTeam: "Cape Verde",
    homeFormation: "4-2-3-1", awayFormation: "4-5-1",
    homeStartXI: [
      {id:1,name:"Emiliano Martínez",number:23,position:"GK"},
      {id:2,name:"Nahuel Molina",number:26,position:"RB"},
      {id:3,name:"Cristian Romero",number:13,position:"CB"},
      {id:4,name:"Lisandro Martínez",number:6,position:"CB"},
      {id:5,name:"Facundo Medina",number:25,position:"LB"},
      {id:6,name:"Rodrigo De Paul",number:7,position:"RM"},
      {id:7,name:"Alexis Mac Allister",number:20,position:"CM"},
      {id:8,name:"Enzo Fernández",number:24,position:"CM"},
      {id:9,name:"Thiago Almada",number:16,position:"LM"},
      {id:10,name:"Lionel Messi",number:10,position:"CF"},
      {id:11,name:"Lautaro Martínez",number:22,position:"CF"},
    ],
    homeSubs: [
      {id:12,name:"Nico González",number:15,position:"MF"},
      {id:13,name:"Julián Alvarez",number:9,position:"FW"},
      {id:14,name:"Leandro Paredes",number:5,position:"MF"},
      {id:15,name:"Nicolás Tagliafico",number:3,position:"DF"},
      {id:16,name:"Gonzalo Montiel",number:4,position:"DF"},
    ],
    awayStartXI: [
      {id:20,name:"Vozinha",number:1,position:"GK"},
      {id:21,name:"Steven Moreira",number:22,position:"RB"},
      {id:22,name:"Pico",number:4,position:"CB"},
      {id:23,name:"Diney",number:3,position:"CB"},
      {id:24,name:"Sidny Lopes Cabral",number:13,position:"LB"},
      {id:25,name:"Kevin Pina",number:6,position:"DM"},
      {id:26,name:"Ryan Mendes",number:20,position:"RM"},
      {id:27,name:"Laros Duarte",number:15,position:"CM"},
      {id:28,name:"Deroy Duarte",number:14,position:"CM"},
      {id:29,name:"Jovane Cabral",number:7,position:"LM"},
      {id:30,name:"Nuno da Costa",number:21,position:"CF"},
    ],
    awaySubs: [
      {id:31,name:"Jamiro Monteiro",number:10,position:"MF"},
      {id:32,name:"Dailon Livramento",number:19,position:"FW"},
      {id:33,name:"Willy Semedo",number:17,position:"MF"},
    ],
  },
  "Colombia_Ghana": {
    homeTeam: "Colombia", awayTeam: "Ghana",
    homeFormation: "4-3-3", awayFormation: "4-5-1",
    homeStartXI: [
      {id:1,name:"Camilo Vargas",number:12,position:"GK"},
      {id:2,name:"Daniel Muñoz",number:2,position:"RB"},
      {id:3,name:"Davinson Sánchez",number:23,position:"CB"},
      {id:4,name:"Jhon Lucumí",number:3,position:"CB"},
      {id:5,name:"Johan Mojica",number:17,position:"LB"},
      {id:6,name:"Jefferson Lerma",number:16,position:"DM"},
      {id:7,name:"Gustavo Puerta",number:14,position:"CM"},
      {id:8,name:"Jhon Arias",number:11,position:"CM"},
      {id:9,name:"James Rodríguez",number:10,position:"RF"},
      {id:10,name:"Jhon Córdoba",number:9,position:"CF"},
      {id:11,name:"Luis Díaz",number:7,position:"LF"},
    ],
    homeSubs: [
      {id:12,name:"Luis Suárez",number:25,position:"FW"},
      {id:13,name:"Richard Ríos",number:6,position:"MF"},
      {id:14,name:"Juan Quintero",number:20,position:"MF"},
      {id:15,name:"Jaminton Campaz",number:21,position:"FW"},
    ],
    awayStartXI: [
      {id:20,name:"Lawrence Ati-Zigi",number:1,position:"GK"},
      {id:21,name:"Marvin Senaya",number:26,position:"RB"},
      {id:22,name:"Derrick Luckassen",number:23,position:"CB"},
      {id:23,name:"Jerome Opoku",number:18,position:"CB"},
      {id:24,name:"Gideon Mensah",number:14,position:"LB"},
      {id:25,name:"Thomas Partey",number:5,position:"DM"},
      {id:26,name:"Caleb Yirenkyi",number:3,position:"CM"},
      {id:27,name:"Kwasi Sibo",number:8,position:"CM"},
      {id:28,name:"Iñaki Williams",number:19,position:"RF"},
      {id:29,name:"Jordan Ayew",number:9,position:"CF"},
      {id:30,name:"Antoine Semenyo",number:11,position:"LF"},
    ],
    awaySubs: [
      {id:31,name:"Abdul Fatawu",number:7,position:"FW"},
      {id:32,name:"Elisha Owusu",number:15,position:"MF"},
      {id:33,name:"Ernest Nuamah",number:24,position:"FW"},
    ],
  },
};
'''

# Insert before fetchMatchLineups function
old = "/** Match lineups via /wc/match/{id}/lineups. */"
new = hardcoded_lineups + "\n/** Match lineups via /wc/match/{id}/lineups. */"

if old in content:
    content = content.replace(old, new, 1)
    with open('src/services/footballData.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Done')
else:
    print('ERROR: marker not found')
