with open('src/services/footballData.ts', encoding='utf-8') as f:
    content = f.read()

group_lineups = '''
  // Group Stage Matchday 1
  "Mexico_South Africa": {
    homeTeam:"Mexico", awayTeam:"South Africa",
    homeFormation:"4-1-4-1", awayFormation:"5-3-2",
    homeStartXI:[
      {id:1,name:"Raúl Rangel",number:1,position:"GK"},
      {id:2,name:"Israel Reyes",number:15,position:"RB"},
      {id:3,name:"César Montes",number:3,position:"CB"},
      {id:4,name:"Johan Vásquez",number:5,position:"CB"},
      {id:5,name:"Jesús Gallardo",number:23,position:"LB"},
      {id:6,name:"Érik Lira",number:6,position:"DM"},
      {id:7,name:"Roberto Alvarado",number:25,position:"RM"},
      {id:8,name:"Álvaro Fidalgo",number:8,position:"CM"},
      {id:9,name:"Brian Gutiérrez",number:26,position:"CM"},
      {id:10,name:"Julián Quiñones",number:16,position:"LM"},
      {id:11,name:"Raúl Jiménez",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Edson Álvarez",number:4,position:"MF"},
      {id:13,name:"Luis Romo",number:7,position:"MF"},
      {id:14,name:"Santiago Giménez",number:11,position:"FW"},
      {id:15,name:"Alexis Vega",number:10,position:"FW"},
      {id:16,name:"Armando González",number:14,position:"FW"},
      {id:17,name:"Gilberto Mora",number:19,position:"MF"},
      {id:18,name:"Luis Chávez",number:24,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Ronwen Williams",number:1,position:"GK"},
      {id:21,name:"Nkosinathi Sibisi",number:19,position:"CB"},
      {id:22,name:"Ime Okon",number:21,position:"CB"},
      {id:23,name:"Mbekezeli Mbokazi",number:14,position:"CB"},
      {id:24,name:"Khuliso Mudau",number:20,position:"RB"},
      {id:25,name:"Aubrey Modiba",number:6,position:"LB"},
      {id:26,name:"Teboho Mokoena",number:4,position:"CM"},
      {id:27,name:"Sphephelo Sithole",number:13,position:"CM"},
      {id:28,name:"Jayden Adams",number:23,position:"CM"},
      {id:29,name:"Lyle Foster",number:9,position:"CF"},
      {id:30,name:"Iqraam Rayners",number:15,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Thalente Mbatha",number:5,position:"MF"},
      {id:32,name:"Themba Zwane",number:11,position:"MF"},
      {id:33,name:"Oswin Appollis",number:7,position:"FW"},
      {id:34,name:"Evidence Makgopa",number:17,position:"FW"},
    ],
  },
  "South Korea_Czech Republic": {
    homeTeam:"South Korea", awayTeam:"Czech Republic",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Kim Seung-gyu",number:1,position:"GK"},
      {id:2,name:"Kim Moon-hwan",number:2,position:"RB"},
      {id:3,name:"Kim Min-jae",number:3,position:"CB"},
      {id:4,name:"Jung Seung-hyun",number:4,position:"CB"},
      {id:5,name:"Kim Jin-su",number:5,position:"LB"},
      {id:6,name:"Hwang In-beom",number:6,position:"CM"},
      {id:7,name:"Jung Woo-young",number:7,position:"CM"},
      {id:8,name:"Lee Jae-sung",number:8,position:"CM"},
      {id:9,name:"Hwang Hee-chan",number:9,position:"RF"},
      {id:10,name:"Son Heung-min",number:10,position:"CF"},
      {id:11,name:"Na Sang-ho",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Cho Gue-sung",number:12,position:"FW"},
      {id:13,name:"Lee Kang-in",number:13,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Tomáš Vaclík",number:1,position:"GK"},
      {id:21,name:"Vladimir Coufal",number:2,position:"RB"},
      {id:22,name:"Tomáš Holeš",number:3,position:"CB"},
      {id:23,name:"Ondřej Kúdela",number:4,position:"CB"},
      {id:24,name:"Jan Bořil",number:5,position:"LB"},
      {id:25,name:"Tomáš Souček",number:6,position:"DM"},
      {id:26,name:"Alex Král",number:7,position:"DM"},
      {id:27,name:"Lukáš Provod",number:8,position:"RW"},
      {id:28,name:"Patrik Schick",number:9,position:"AM"},
      {id:29,name:"Ondřej Lingr",number:10,position:"LW"},
      {id:30,name:"Adam Hložek",number:11,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Jan Kuchta",number:12,position:"FW"},
      {id:32,name:"Marek Suchý",number:13,position:"DF"},
    ],
  },
  "Canada_Bosnia & Herzegovina": {
    homeTeam:"Canada", awayTeam:"Bosnia & Herzegovina",
    homeFormation:"4-4-2", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Maxime Crépeau",number:16,position:"GK"},
      {id:2,name:"Alistair Johnston",number:2,position:"RB"},
      {id:3,name:"Moïse Bombito",number:15,position:"CB"},
      {id:4,name:"Derek Cornelius",number:13,position:"CB"},
      {id:5,name:"Richie Laryea",number:22,position:"LB"},
      {id:6,name:"Tajon Buchanan",number:17,position:"RM"},
      {id:7,name:"Nathan Saliba",number:25,position:"CM"},
      {id:8,name:"Stephen Eustáquio",number:7,position:"CM"},
      {id:9,name:"Liam Millar",number:11,position:"LM"},
      {id:10,name:"Jonathan David",number:10,position:"CF"},
      {id:11,name:"Tani Oluwaseyi",number:12,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Alphonso Davies",number:19,position:"DF"},
      {id:13,name:"Jacob Shaffelburg",number:14,position:"MF"},
      {id:14,name:"Promise David",number:24,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Nikola Vasilj",number:1,position:"GK"},
      {id:21,name:"Amar Dedić",number:7,position:"RB"},
      {id:22,name:"Nikola Katić",number:18,position:"CB"},
      {id:23,name:"Tarik Muharemović",number:4,position:"CB"},
      {id:24,name:"Sead Kolašinac",number:5,position:"LB"},
      {id:25,name:"Armin Gigović",number:8,position:"RM"},
      {id:26,name:"Ivan Šunjić",number:14,position:"CM"},
      {id:27,name:"Kerim Alajbegović",number:19,position:"CM"},
      {id:28,name:"Esmir Bajraktarević",number:20,position:"LM"},
      {id:29,name:"Edin Džeko",number:11,position:"CF"},
      {id:30,name:"Ermedin Demirović",number:10,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Benjamin Tahirović",number:6,position:"MF"},
      {id:32,name:"Haris Tabaković",number:23,position:"FW"},
    ],
  },
  "Qatar_Switzerland": {
    homeTeam:"Qatar", awayTeam:"Switzerland",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Meshaal Barsham",number:1,position:"GK"},
      {id:2,name:"Pedro Miguel",number:2,position:"RB"},
      {id:3,name:"Tarek Salman",number:3,position:"CB"},
      {id:4,name:"Bassam Al-Rawi",number:4,position:"CB"},
      {id:5,name:"Homam Ahmed",number:5,position:"LB"},
      {id:6,name:"Karim Boudiaf",number:6,position:"CM"},
      {id:7,name:"Abdulaziz Hatem",number:7,position:"CM"},
      {id:8,name:"Hassan Al-Haydos",number:8,position:"CM"},
      {id:9,name:"Akram Afif",number:9,position:"RF"},
      {id:10,name:"Almoez Ali",number:10,position:"CF"},
      {id:11,name:"Mohammed Muntari",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Yusuf Abdurisag",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Gregor Kobel",number:1,position:"GK"},
      {id:21,name:"Denis Zakaria",number:6,position:"RB"},
      {id:22,name:"Nico Elvedi",number:4,position:"CB"},
      {id:23,name:"Manuel Akanji",number:5,position:"CB"},
      {id:24,name:"Ricardo Rodriguez",number:13,position:"LB"},
      {id:25,name:"Remo Freuler",number:8,position:"CM"},
      {id:26,name:"Granit Xhaka",number:10,position:"CM"},
      {id:27,name:"Dan Ndoye",number:11,position:"RW"},
      {id:28,name:"Johan Manzambi",number:9,position:"AM"},
      {id:29,name:"Rubén Vargas",number:17,position:"LW"},
      {id:30,name:"Breel Embolo",number:7,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Noah Okafor",number:19,position:"FW"},
      {id:32,name:"Fabian Rieder",number:22,position:"MF"},
    ],
  },
  "Brazil_Morocco": {
    homeTeam:"Brazil", awayTeam:"Morocco",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Alisson",number:1,position:"GK"},
      {id:2,name:"Danilo Luiz",number:13,position:"RB"},
      {id:3,name:"Marquinhos",number:4,position:"CB"},
      {id:4,name:"Gabriel Magalhães",number:3,position:"CB"},
      {id:5,name:"Douglas Santos",number:16,position:"LB"},
      {id:6,name:"Casemiro",number:5,position:"DM"},
      {id:7,name:"Bruno Guimarães",number:8,position:"CM"},
      {id:8,name:"Lucas Paquetá",number:20,position:"CM"},
      {id:9,name:"Rayan",number:26,position:"RF"},
      {id:10,name:"Matheus Cunha",number:9,position:"CF"},
      {id:11,name:"Vinícius Júnior",number:7,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Endrick",number:19,position:"FW"},
      {id:13,name:"Gabriel Martinelli",number:22,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Yassine Bounou",number:1,position:"GK"},
      {id:21,name:"Achraf Hakimi",number:2,position:"RB"},
      {id:22,name:"Issa Diop",number:14,position:"CB"},
      {id:23,name:"Chadi Riad",number:18,position:"CB"},
      {id:24,name:"Noussair Mazraoui",number:3,position:"LB"},
      {id:25,name:"Ayyoub Bouaddi",number:6,position:"CM"},
      {id:26,name:"Neil El Aynaoui",number:24,position:"CM"},
      {id:27,name:"Brahim Díaz",number:10,position:"RW"},
      {id:28,name:"Azzedine Ounahi",number:8,position:"AM"},
      {id:29,name:"Bilal El Khannouss",number:23,position:"LW"},
      {id:30,name:"Ismael Saibari",number:11,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Soufiane Rahimi",number:9,position:"FW"},
      {id:32,name:"Chemsdine Talbi",number:7,position:"MF"},
    ],
  },
  "Haiti_Scotland": {
    homeTeam:"Haiti", awayTeam:"Scotland",
    homeFormation:"4-4-2", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Josué Duverger",number:1,position:"GK"},
      {id:2,name:"Mechack Jérôme",number:2,position:"RB"},
      {id:3,name:"Steeven Saba",number:3,position:"CB"},
      {id:4,name:"Zachary Herivaux",number:4,position:"CB"},
      {id:5,name:"Andrew Jean-Baptiste",number:5,position:"LB"},
      {id:6,name:"Duckens Nazon",number:6,position:"RM"},
      {id:7,name:"Wilde-Donald Guerrier",number:7,position:"CM"},
      {id:8,name:"Mickaël Biron",number:8,position:"CM"},
      {id:9,name:"Frantzdy Pierrot",number:9,position:"LM"},
      {id:10,name:"Carnejy Antoine",number:10,position:"CF"},
      {id:11,name:"Kevin Lafrance",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Derrick Étienne",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Angus Gunn",number:1,position:"GK"},
      {id:21,name:"Aaron Hickey",number:2,position:"RB"},
      {id:22,name:"Grant Hanley",number:3,position:"CB"},
      {id:23,name:"Scott McKenna",number:4,position:"CB"},
      {id:24,name:"Andrew Robertson",number:5,position:"LB"},
      {id:25,name:"Billy Gilmour",number:6,position:"CM"},
      {id:26,name:"John McGinn",number:7,position:"CM"},
      {id:27,name:"Stuart Armstrong",number:8,position:"CM"},
      {id:28,name:"Ryan Christie",number:9,position:"RW"},
      {id:29,name:"Che Adams",number:10,position:"CF"},
      {id:30,name:"Ryan Gauld",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Lyndon Dykes",number:12,position:"FW"},
      {id:32,name:"Kenny McLean",number:13,position:"MF"},
    ],
  },
  "USA_Paraguay": {
    homeTeam:"USA", awayTeam:"Paraguay",
    homeFormation:"3-4-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Matt Freese",number:24,position:"GK"},
      {id:2,name:"Alex Freeman",number:16,position:"CB"},
      {id:3,name:"Chris Richards",number:3,position:"CB"},
      {id:4,name:"Tim Ream",number:13,position:"CB"},
      {id:5,name:"Sergiño Dest",number:2,position:"RM"},
      {id:6,name:"Weston McKennie",number:8,position:"CM"},
      {id:7,name:"Tyler Adams",number:4,position:"CM"},
      {id:8,name:"Antonee Robinson",number:5,position:"LM"},
      {id:9,name:"Christian Pulisic",number:10,position:"RF"},
      {id:10,name:"Folarin Balogun",number:20,position:"CF"},
      {id:11,name:"Malik Tillman",number:17,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ricardo Pepi",number:9,position:"FW"},
      {id:13,name:"Giovanni Reyna",number:7,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Orlando Gill",number:12,position:"GK"},
      {id:21,name:"Juan José Cáceres",number:4,position:"RB"},
      {id:22,name:"Gustavo Gómez",number:15,position:"CB"},
      {id:23,name:"José Canale",number:13,position:"CB"},
      {id:24,name:"Júnior Alonso",number:6,position:"LB"},
      {id:25,name:"Miguel Almirón",number:10,position:"RM"},
      {id:26,name:"Damián Bobadilla",number:16,position:"CM"},
      {id:27,name:"Andrés Cubas",number:14,position:"CM"},
      {id:28,name:"Matías Galarza",number:23,position:"LM"},
      {id:29,name:"Gabriel Ávalos",number:21,position:"CF"},
      {id:30,name:"Julio Enciso",number:19,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Antonio Sanabria",number:9,position:"FW"},
      {id:32,name:"Maurício",number:11,position:"MF"},
    ],
  },
  "Australia_Turkey": {
    homeTeam:"Australia", awayTeam:"Turkey",
    homeFormation:"3-4-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Patrick Beach",number:18,position:"GK"},
      {id:2,name:"Alessandro Circati",number:3,position:"CB"},
      {id:3,name:"Harry Souttar",number:19,position:"CB"},
      {id:4,name:"Lucas Herrington",number:25,position:"CB"},
      {id:5,name:"Jordan Bos",number:5,position:"RM"},
      {id:6,name:"Jackson Irvine",number:22,position:"CM"},
      {id:7,name:"Aiden O\'Neill",number:13,position:"CM"},
      {id:8,name:"Aziz Behich",number:16,position:"LM"},
      {id:9,name:"Cristian Volpato",number:20,position:"RF"},
      {id:10,name:"Nestory Irankunda",number:17,position:"CF"},
      {id:11,name:"Connor Metcalfe",number:8,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ajdin Hrustic",number:10,position:"FW"},
      {id:13,name:"Mohamed Touré",number:9,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Altay Bayındır",number:1,position:"GK"},
      {id:21,name:"Zeki Çelik",number:2,position:"RB"},
      {id:22,name:"Merih Demiral",number:3,position:"CB"},
      {id:23,name:"Samet Akaydın",number:4,position:"CB"},
      {id:24,name:"Ferdi Kadıoğlu",number:5,position:"LB"},
      {id:25,name:"Hakan Çalhanoğlu",number:8,position:"DM"},
      {id:26,name:"Salih Özcan",number:6,position:"CM"},
      {id:27,name:"Kerem Aktürkoğlu",number:7,position:"RW"},
      {id:28,name:"Arda Güler",number:10,position:"AM"},
      {id:29,name:"Baris Alper Yilmaz",number:11,position:"LW"},
      {id:30,name:"Cenk Tosun",number:9,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Burak Yılmaz",number:12,position:"FW"},
      {id:32,name:"Okay Yokuşlu",number:13,position:"MF"},
    ],
  },
  "Germany_Curacao": {
    homeTeam:"Germany", awayTeam:"Curacao",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Manuel Neuer",number:1,position:"GK"},
      {id:2,name:"Joshua Kimmich",number:6,position:"RB"},
      {id:3,name:"Jonathan Tah",number:4,position:"CB"},
      {id:4,name:"Antonio Rüdiger",number:2,position:"CB"},
      {id:5,name:"Nathaniel Brown",number:18,position:"LB"},
      {id:6,name:"Felix Nmecha",number:23,position:"CM"},
      {id:7,name:"Aleksandar Pavlović",number:5,position:"CM"},
      {id:8,name:"Leroy Sané",number:19,position:"RW"},
      {id:9,name:"Kai Havertz",number:7,position:"AM"},
      {id:10,name:"Florian Wirtz",number:17,position:"LW"},
      {id:11,name:"Deniz Undav",number:26,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Leon Goretzka",number:8,position:"MF"},
      {id:13,name:"Jamal Musiala",number:10,position:"MF"},
      {id:14,name:"Nick Woltemade",number:11,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Eloy Room",number:1,position:"GK"},
      {id:21,name:"Cuco Martina",number:2,position:"RB"},
      {id:22,name:"Ethan Flemming",number:3,position:"CB"},
      {id:23,name:"Rangelo Janga",number:4,position:"CB"},
      {id:24,name:"Jurien Gaari",number:5,position:"LB"},
      {id:25,name:"Jarchinio Antonia",number:6,position:"CM"},
      {id:26,name:"Leandro Bacuna",number:7,position:"CM"},
      {id:27,name:"Cuco Martina Jr.",number:8,position:"CM"},
      {id:28,name:"Gevaro Nepomuceno",number:9,position:"RW"},
      {id:29,name:"Gino van Kessel",number:10,position:"CF"},
      {id:30,name:"Quentin Bautista",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Jafar Arias",number:12,position:"FW"},
    ],
  },
  "Netherlands_Japan": {
    homeTeam:"Netherlands", awayTeam:"Japan",
    homeFormation:"3-4-3", awayFormation:"3-4-3",
    homeStartXI:[
      {id:1,name:"Bart Verbruggen",number:1,position:"GK"},
      {id:2,name:"Jan Paul van Hecke",number:6,position:"CB"},
      {id:3,name:"Virgil van Dijk",number:4,position:"CB"},
      {id:4,name:"Nathan Aké",number:5,position:"CB"},
      {id:5,name:"Denzel Dumfries",number:22,position:"RM"},
      {id:6,name:"Ryan Gravenberch",number:8,position:"CM"},
      {id:7,name:"Frenkie de Jong",number:21,position:"CM"},
      {id:8,name:"Micky van de Ven",number:15,position:"LM"},
      {id:9,name:"Crysencio Summerville",number:24,position:"RF"},
      {id:10,name:"Brian Brobbey",number:19,position:"CF"},
      {id:11,name:"Cody Gakpo",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Teun Koopmeiners",number:20,position:"MF"},
      {id:13,name:"Wout Weghorst",number:9,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Zion Suzuki",number:1,position:"GK"},
      {id:21,name:"Takehiro Tomiyasu",number:22,position:"CB"},
      {id:22,name:"Shōgo Taniguchi",number:3,position:"CB"},
      {id:23,name:"Hiroki Itō",number:21,position:"CB"},
      {id:24,name:"Ritsu Dōan",number:10,position:"RM"},
      {id:25,name:"Kaishū Sano",number:24,position:"CM"},
      {id:26,name:"Daichi Kamada",number:15,position:"CM"},
      {id:27,name:"Keito Nakamura",number:13,position:"LM"},
      {id:28,name:"Junya Itō",number:14,position:"RF"},
      {id:29,name:"Ayase Ueda",number:18,position:"CF"},
      {id:30,name:"Daizen Maeda",number:11,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Ao Tanaka",number:7,position:"MF"},
      {id:32,name:"Kōki Ogawa",number:19,position:"FW"},
    ],
  },
  "Ivory Coast_Ecuador": {
    homeTeam:"Ivory Coast", awayTeam:"Ecuador",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Yahia Fofana",number:1,position:"GK"},
      {id:2,name:"Guéla Doué",number:17,position:"RB"},
      {id:3,name:"Odilon Kossounou",number:7,position:"CB"},
      {id:4,name:"Emmanuel Agbadou",number:20,position:"CB"},
      {id:5,name:"Ghislain Konan",number:3,position:"LB"},
      {id:6,name:"Ibrahim Sangaré",number:18,position:"DM"},
      {id:7,name:"Franck Kessié",number:8,position:"CM"},
      {id:8,name:"Nicolas Pépé",number:19,position:"RF"},
      {id:9,name:"Ange-Yoan Bonny",number:9,position:"CF"},
      {id:10,name:"Yan Diomande",number:11,position:"LF"},
      {id:11,name:"Christ Inao Oulaï",number:26,position:"CM"},
    ],
    homeSubs:[
      {id:12,name:"Amad Diallo",number:15,position:"FW"},
      {id:13,name:"Elye Wahi",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Hernán Galíndez",number:1,position:"GK"},
      {id:21,name:"Piero Hincapié",number:3,position:"LB"},
      {id:22,name:"Willian Pacho",number:6,position:"CB"},
      {id:23,name:"Joel Ordóñez",number:4,position:"CB"},
      {id:24,name:"Ángelo Preciado",number:17,position:"RB"},
      {id:25,name:"Moisés Caicedo",number:23,position:"CM"},
      {id:26,name:"Pedro Vite",number:15,position:"CM"},
      {id:27,name:"Nilson Angulo",number:20,position:"LM"},
      {id:28,name:"John Yeboah",number:9,position:"RM"},
      {id:29,name:"Gonzalo Plata",number:19,position:"CF"},
      {id:30,name:"Enner Valencia",number:13,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Kendry Páez",number:10,position:"MF"},
      {id:32,name:"Kevin Rodríguez",number:11,position:"FW"},
    ],
  },
  "Sweden_Tunisia": {
    homeTeam:"Sweden", awayTeam:"Tunisia",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Jacob Widell Zetterström",number:1,position:"GK"},
      {id:2,name:"Daniel Svensson",number:8,position:"RB"},
      {id:3,name:"Gustaf Lagerbielke",number:2,position:"CB"},
      {id:4,name:"Victor Lindelöf",number:3,position:"CB"},
      {id:5,name:"Gabriel Gudmundsson",number:5,position:"LB"},
      {id:6,name:"Anthony Elanga",number:11,position:"RM"},
      {id:7,name:"Lucas Bergvall",number:7,position:"CM"},
      {id:8,name:"Yasin Ayari",number:18,position:"CM"},
      {id:9,name:"Elliot Stroud",number:24,position:"LM"},
      {id:10,name:"Viktor Gyökeres",number:17,position:"CF"},
      {id:11,name:"Alexander Isak",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Taha Ali",number:26,position:"FW"},
      {id:13,name:"Besfort Zeneli",number:22,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Aymen Dahmen",number:1,position:"GK"},
      {id:21,name:"Mohamed Drager",number:2,position:"RB"},
      {id:22,name:"Montassar Talbi",number:3,position:"CB"},
      {id:23,name:"Yassine Meriah",number:4,position:"CB"},
      {id:24,name:"Ali Abdi",number:5,position:"LB"},
      {id:25,name:"Ellyes Skhiri",number:6,position:"CM"},
      {id:26,name:"Aissa Laidouni",number:7,position:"CM"},
      {id:27,name:"Wahbi Khazri",number:8,position:"CM"},
      {id:28,name:"Hannibal Mejbri",number:9,position:"RW"},
      {id:29,name:"Issam Jebali",number:10,position:"CF"},
      {id:30,name:"Seifeddine Jaziri",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Naïm Sliti",number:12,position:"MF"},
    ],
  },
  "Spain_Cape Verde": {
    homeTeam:"Spain", awayTeam:"Cape Verde",
    homeFormation:"4-3-3", awayFormation:"4-5-1",
    homeStartXI:[
      {id:1,name:"Unai Simón",number:23,position:"GK"},
      {id:2,name:"Pedro Porro",number:12,position:"RB"},
      {id:3,name:"Pau Cubarsí",number:22,position:"CB"},
      {id:4,name:"Aymeric Laporte",number:14,position:"CB"},
      {id:5,name:"Marc Cucurella",number:24,position:"LB"},
      {id:6,name:"Rodri",number:16,position:"DM"},
      {id:7,name:"Dani Olmo",number:10,position:"CM"},
      {id:8,name:"Pedri",number:20,position:"CM"},
      {id:9,name:"Lamine Yamal",number:19,position:"RF"},
      {id:10,name:"Mikel Oyarzabal",number:21,position:"CF"},
      {id:11,name:"Álex Baena",number:15,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ferran Torres",number:7,position:"FW"},
      {id:13,name:"Mikel Merino",number:6,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Vozinha",number:1,position:"GK"},
      {id:21,name:"Steven Moreira",number:22,position:"RB"},
      {id:22,name:"Pico",number:4,position:"CB"},
      {id:23,name:"Diney",number:3,position:"CB"},
      {id:24,name:"Sidny Lopes Cabral",number:13,position:"LB"},
      {id:25,name:"Kevin Pina",number:6,position:"DM"},
      {id:26,name:"Ryan Mendes",number:20,position:"RM"},
      {id:27,name:"Laros Duarte",number:15,position:"CM"},
      {id:28,name:"Deroy Duarte",number:14,position:"CM"},
      {id:29,name:"Jovane Cabral",number:7,position:"LM"},
      {id:30,name:"Nuno da Costa",number:21,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Jamiro Monteiro",number:10,position:"MF"},
      {id:32,name:"Dailon Livramento",number:19,position:"FW"},
    ],
  },
  "Belgium_Egypt": {
    homeTeam:"Belgium", awayTeam:"Egypt",
    homeFormation:"4-2-3-1", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Thibaut Courtois",number:1,position:"GK"},
      {id:2,name:"Timothy Castagne",number:21,position:"RB"},
      {id:3,name:"Brandon Mechele",number:4,position:"CB"},
      {id:4,name:"Arthur Theate",number:3,position:"CB"},
      {id:5,name:"Maxim De Cuyper",number:5,position:"LB"},
      {id:6,name:"Hans Vanaken",number:20,position:"CM"},
      {id:7,name:"Youri Tielemans",number:8,position:"CM"},
      {id:8,name:"Leandro Trossard",number:10,position:"RW"},
      {id:9,name:"Kevin De Bruyne",number:7,position:"AM"},
      {id:10,name:"Jérémy Doku",number:11,position:"LW"},
      {id:11,name:"Charles De Ketelaere",number:17,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Romelu Lukaku",number:9,position:"FW"},
      {id:13,name:"Dodi Lukébakio",number:14,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Mostafa Shobeir",number:23,position:"GK"},
      {id:21,name:"Mohamed Hany",number:3,position:"RB"},
      {id:22,name:"Yasser Ibrahim",number:2,position:"CB"},
      {id:23,name:"Ramy Rabia",number:5,position:"CB"},
      {id:24,name:"Karim Hafez",number:15,position:"LB"},
      {id:25,name:"Emam Ashour",number:8,position:"RM"},
      {id:26,name:"Hamdy Fathy",number:14,position:"CM"},
      {id:27,name:"Marwan Attia",number:19,position:"CM"},
      {id:28,name:"Mostafa Ziko",number:11,position:"LM"},
      {id:29,name:"Mohamed Salah",number:10,position:"CF"},
      {id:30,name:"Omar Marmoush",number:22,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Haissem Hassan",number:12,position:"FW"},
      {id:32,name:"Hossam Abdelmaguid",number:4,position:"DF"},
    ],
  },
  "Saudi Arabia_Uruguay": {
    homeTeam:"Saudi Arabia", awayTeam:"Uruguay",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Mohammed Al-Owais",number:1,position:"GK"},
      {id:2,name:"Saud Abdulhamid",number:2,position:"RB"},
      {id:3,name:"Ali Al-Bulaihi",number:3,position:"CB"},
      {id:4,name:"Abdulelah Al-Amri",number:4,position:"CB"},
      {id:5,name:"Yasser Al-Shahrani",number:5,position:"LB"},
      {id:6,name:"Salman Al-Faraj",number:6,position:"CM"},
      {id:7,name:"Abdulrahman Al-Aboud",number:7,position:"CM"},
      {id:8,name:"Sami Al-Naji",number:8,position:"CM"},
      {id:9,name:"Salem Al-Dawsari",number:9,position:"RW"},
      {id:10,name:"Firas Al-Buraikan",number:10,position:"CF"},
      {id:11,name:"Mohammed Al-Buraikan",number:11,position:"LW"},
    ],
    homeSubs:[
      {id:12,name:"Ali Al-Hassan",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Sergio Rochet",number:1,position:"GK"},
      {id:21,name:"Nahitan Nández",number:2,position:"RB"},
      {id:22,name:"José María Giménez",number:3,position:"CB"},
      {id:23,name:"Ronald Araújo",number:4,position:"CB"},
      {id:24,name:"Mathías Olivera",number:5,position:"LB"},
      {id:25,name:"Lucas Torreira",number:6,position:"DM"},
      {id:26,name:"Rodrigo Bentancur",number:7,position:"CM"},
      {id:27,name:"Federico Valverde",number:8,position:"CM"},
      {id:28,name:"Facundo Pellistri",number:9,position:"RW"},
      {id:29,name:"Darwin Núñez",number:10,position:"CF"},
      {id:30,name:"Maximiliano Araújo",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Edinson Cavani",number:12,position:"FW"},
      {id:32,name:"Giorgian de Arrascaeta",number:13,position:"MF"},
    ],
  },
  "Iran_New Zealand": {
    homeTeam:"Iran", awayTeam:"New Zealand",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Alireza Beiranvand",number:1,position:"GK"},
      {id:2,name:"Sadegh Moharrami",number:2,position:"RB"},
      {id:3,name:"Shoja Khalilzadeh",number:3,position:"CB"},
      {id:4,name:"Morteza Pouraliganji",number:4,position:"CB"},
      {id:5,name:"Milad Mohammadi",number:5,position:"LB"},
      {id:6,name:"Saeid Ezatolahi",number:6,position:"CM"},
      {id:7,name:"Mehdi Torabi",number:7,position:"CM"},
      {id:8,name:"Ali Karimi",number:8,position:"CM"},
      {id:9,name:"Sardar Azmoun",number:9,position:"RF"},
      {id:10,name:"Mehdi Taremi",number:10,position:"CF"},
      {id:11,name:"Allahyar Sayyadmanesh",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ahmad Noorollahi",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Oliver Sail",number:1,position:"GK"},
      {id:21,name:"Liberato Cacace",number:2,position:"RB"},
      {id:22,name:"Niko Kirwan",number:3,position:"CB"},
      {id:23,name:"Winston Reid",number:4,position:"CB"},
      {id:24,name:"Michael Boxall",number:5,position:"LB"},
      {id:25,name:"Marko Stamenic",number:6,position:"CM"},
      {id:26,name:"Liam McGing",number:7,position:"CM"},
      {id:27,name:"Clayton Lewis",number:8,position:"CM"},
      {id:28,name:"Elijah Just",number:9,position:"RW"},
      {id:29,name:"Chris Wood",number:10,position:"CF"},
      {id:30,name:"Ben Old",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Kosta Barbarouses",number:12,position:"FW"},
    ],
  },
  "France_Senegal": {
    homeTeam:"France", awayTeam:"Senegal",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Mike Maignan",number:16,position:"GK"},
      {id:2,name:"Jules Koundé",number:5,position:"RB"},
      {id:3,name:"Dayot Upamecano",number:4,position:"CB"},
      {id:4,name:"William Saliba",number:17,position:"CB"},
      {id:5,name:"Lucas Digne",number:3,position:"LB"},
      {id:6,name:"Aurélien Tchouaméni",number:8,position:"CM"},
      {id:7,name:"Adrien Rabiot",number:14,position:"CM"},
      {id:8,name:"Ousmane Dembélé",number:7,position:"RW"},
      {id:9,name:"Michael Olise",number:11,position:"AM"},
      {id:10,name:"Bradley Barcola",number:12,position:"LW"},
      {id:11,name:"Kylian Mbappé",number:10,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Désiré Doué",number:20,position:"FW"},
      {id:13,name:"Rayan Cherki",number:24,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Mory Diaw",number:23,position:"GK"},
      {id:21,name:"Krépin Diatta",number:15,position:"RB"},
      {id:22,name:"Pathé Ciss",number:6,position:"CB"},
      {id:23,name:"Moussa Niakhaté",number:19,position:"CB"},
      {id:24,name:"Ismail Jakobs",number:14,position:"LB"},
      {id:25,name:"Habib Diarra",number:21,position:"CM"},
      {id:26,name:"Idrissa Gueye",number:5,position:"CM"},
      {id:27,name:"Pape Gueye",number:26,position:"CM"},
      {id:28,name:"Iliman Ndiaye",number:13,position:"RF"},
      {id:29,name:"Ismaïla Sarr",number:18,position:"CF"},
      {id:30,name:"Sadio Mané",number:10,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Lamine Camara",number:8,position:"MF"},
      {id:32,name:"Nicolas Jackson",number:11,position:"FW"},
    ],
  },
  "Iraq_Norway": {
    homeTeam:"Iraq", awayTeam:"Norway",
    homeFormation:"4-4-2", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Jalal Hassan",number:1,position:"GK"},
      {id:2,name:"Ali Adnan",number:2,position:"LB"},
      {id:3,name:"Salam Shakir",number:3,position:"CB"},
      {id:4,name:"Hussein Ali",number:4,position:"CB"},
      {id:5,name:"Ali Jasim",number:5,position:"RB"},
      {id:6,name:"Amjed Attwan",number:6,position:"RM"},
      {id:7,name:"Bashar Resan",number:7,position:"CM"},
      {id:8,name:"Aymen Hussein",number:8,position:"CM"},
      {id:9,name:"Ibrahim Bayesh",number:9,position:"LM"},
      {id:10,name:"Mohanad Ali",number:10,position:"CF"},
      {id:11,name:"Ahmed Yasin",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Alaa Abbas",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Ørjan Nyland",number:1,position:"GK"},
      {id:21,name:"Marcus Holmgren Pedersen",number:16,position:"RB"},
      {id:22,name:"Kristoffer Ajer",number:3,position:"CB"},
      {id:23,name:"Torbjørn Heggem",number:17,position:"CB"},
      {id:24,name:"David Møller Wolfe",number:5,position:"LB"},
      {id:25,name:"Patrick Berg",number:6,position:"CM"},
      {id:26,name:"Sander Berge",number:8,position:"CM"},
      {id:27,name:"Martin Ødegaard",number:10,position:"AM"},
      {id:28,name:"Alexander Sørloth",number:7,position:"RF"},
      {id:29,name:"Erling Haaland",number:9,position:"CF"},
      {id:30,name:"Antonio Nusa",number:20,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Oscar Bobb",number:22,position:"MF"},
      {id:32,name:"Andreas Schjelderup",number:21,position:"MF"},
    ],
  },
  "Argentina_Algeria": {
    homeTeam:"Argentina", awayTeam:"Algeria",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Emiliano Martínez",number:23,position:"GK"},
      {id:2,name:"Nahuel Molina",number:26,position:"RB"},
      {id:3,name:"Cristian Romero",number:13,position:"CB"},
      {id:4,name:"Lisandro Martínez",number:6,position:"CB"},
      {id:5,name:"Facundo Medina",number:25,position:"LB"},
      {id:6,name:"Rodrigo De Paul",number:7,position:"RM"},
      {id:7,name:"Alexis Mac Allister",number:20,position:"CM"},
      {id:8,name:"Enzo Fernández",number:24,position:"CM"},
      {id:9,name:"Thiago Almada",number:16,position:"LM"},
      {id:10,name:"Lionel Messi",number:10,position:"CF"},
      {id:11,name:"Lautaro Martínez",number:22,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Julián Alvarez",number:9,position:"FW"},
      {id:13,name:"Leandro Paredes",number:5,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Luca Zidane",number:23,position:"GK"},
      {id:21,name:"Rafik Belghali",number:17,position:"RB"},
      {id:22,name:"Aïssa Mandi",number:2,position:"CB"},
      {id:23,name:"Ramy Bensebaini",number:21,position:"CB"},
      {id:24,name:"Rayan Aït-Nouri",number:15,position:"LB"},
      {id:25,name:"Nabil Bentaleb",number:19,position:"DM"},
      {id:26,name:"Ramiz Zerrouki",number:6,position:"CM"},
      {id:27,name:"Farès Chaïbi",number:10,position:"CM"},
      {id:28,name:"Riyad Mahrez",number:7,position:"RF"},
      {id:29,name:"Ibrahim Maza",number:22,position:"CF"},
      {id:30,name:"Houssem Aouar",number:8,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Amine Gouiri",number:9,position:"FW"},
      {id:32,name:"Anis Hadj Moussa",number:11,position:"FW"},
    ],
  },
  "Austria_Jordan": {
    homeTeam:"Austria", awayTeam:"Jordan",
    homeFormation:"4-2-3-1", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Alexander Schlager",number:1,position:"GK"},
      {id:2,name:"Stefan Posch",number:5,position:"RB"},
      {id:3,name:"Kevin Danso",number:3,position:"CB"},
      {id:4,name:"David Alaba",number:8,position:"CB"},
      {id:5,name:"Konrad Laimer",number:20,position:"LB"},
      {id:6,name:"Nicolas Seiwald",number:6,position:"CM"},
      {id:7,name:"Xaver Schlager",number:4,position:"CM"},
      {id:8,name:"Romano Schmid",number:18,position:"RW"},
      {id:9,name:"Paul Wanner",number:24,position:"AM"},
      {id:10,name:"Marcel Sabitzer",number:9,position:"LW"},
      {id:11,name:"Michael Gregoritsch",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Marko Arnautović",number:7,position:"FW"},
      {id:13,name:"Florian Grillitsch",number:10,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Yazeed Abulaila",number:1,position:"GK"},
      {id:21,name:"Baha Faisal",number:2,position:"RB"},
      {id:22,name:"Anas Bani Yaseen",number:3,position:"CB"},
      {id:23,name:"Yazan Al-Naimat",number:4,position:"CB"},
      {id:24,name:"Ahmad Ibrahim",number:5,position:"LB"},
      {id:25,name:"Nizar Al-Rashdan",number:6,position:"CM"},
      {id:26,name:"Musa Al-Tamari",number:7,position:"CM"},
      {id:27,name:"Salem Al-Ajalin",number:8,position:"CM"},
      {id:28,name:"Hamza Al-Dardour",number:9,position:"RW"},
      {id:29,name:"Yazan Al-Arab",number:10,position:"CF"},
      {id:30,name:"Zaid Al-Rashdan",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Ahmad Habashneh",number:12,position:"FW"},
    ],
  },
  "Portugal_D.R. Congo": {
    homeTeam:"Portugal", awayTeam:"D.R. Congo",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Diogo Costa",number:1,position:"GK"},
      {id:2,name:"João Cancelo",number:20,position:"RB"},
      {id:3,name:"Rúben Dias",number:3,position:"CB"},
      {id:4,name:"Renato Veiga",number:13,position:"CB"},
      {id:5,name:"Nuno Mendes",number:25,position:"LB"},
      {id:6,name:"João Neves",number:15,position:"CM"},
      {id:7,name:"Vitinha",number:23,position:"CM"},
      {id:8,name:"Bruno Fernandes",number:8,position:"AM"},
      {id:9,name:"Pedro Neto",number:18,position:"RW"},
      {id:10,name:"Rafael Leão",number:17,position:"LW"},
      {id:11,name:"Cristiano Ronaldo",number:7,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Gonçalo Ramos",number:9,position:"FW"},
      {id:13,name:"Bernardo Silva",number:10,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Lionel Mpasi",number:1,position:"GK"},
      {id:21,name:"Aaron Wan-Bissaka",number:2,position:"RB"},
      {id:22,name:"Chancel Mbemba",number:22,position:"CB"},
      {id:23,name:"Axel Tuanzebe",number:4,position:"CB"},
      {id:24,name:"Arthur Masuaku",number:26,position:"LB"},
      {id:25,name:"Samuel Moutoussamy",number:8,position:"DM"},
      {id:26,name:"Nathanaël Mbuku",number:7,position:"RM"},
      {id:27,name:"Ngal\'ayel Mukau",number:6,position:"CM"},
      {id:28,name:"Noah Sadiki",number:14,position:"CM"},
      {id:29,name:"Brian Cipenga",number:9,position:"LM"},
      {id:30,name:"Yoane Wissa",number:20,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Meschak Elia",number:13,position:"FW"},
      {id:32,name:"Théo Bongonda",number:10,position:"MF"},
    ],
  },
  "England_Croatia": {
    homeTeam:"England", awayTeam:"Croatia",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Jordan Pickford",number:1,position:"GK"},
      {id:2,name:"Djed Spence",number:25,position:"RB"},
      {id:3,name:"Ezri Konsa",number:2,position:"CB"},
      {id:4,name:"Marc Guéhi",number:6,position:"CB"},
      {id:5,name:"Nico O'Reilly",number:3,position:"LB"},
      {id:6,name:"Elliot Anderson",number:8,position:"CM"},
      {id:7,name:"Declan Rice",number:4,position:"CM"},
      {id:8,name:"Noni Madueke",number:20,position:"RW"},
      {id:9,name:"Jude Bellingham",number:10,position:"AM"},
      {id:10,name:"Marcus Rashford",number:11,position:"LW"},
      {id:11,name:"Harry Kane",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Bukayo Saka",number:7,position:"FW"},
      {id:13,name:"Anthony Gordon",number:18,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Dominik Livaković",number:1,position:"GK"},
      {id:21,name:"Josip Stanišić",number:2,position:"RB"},
      {id:22,name:"Josip Šutalo",number:6,position:"CB"},
      {id:23,name:"Marin Pongračić",number:3,position:"CB"},
      {id:24,name:"Ivan Perišić",number:14,position:"LB"},
      {id:25,name:"Luka Modrić",number:10,position:"CM"},
      {id:26,name:"Mateo Kovačić",number:8,position:"CM"},
      {id:27,name:"Nikola Vlašić",number:13,position:"RW"},
      {id:28,name:"Petar Sučić",number:17,position:"AM"},
      {id:29,name:"Martin Baturina",number:16,position:"LW"},



cat > fix_all_group_lineups.py << 'EOF'
with open('src/services/footballData.ts', encoding='utf-8') as f:
    content = f.read()

group_lineups = '''
  // Group Stage Matchday 1
  "Mexico_South Africa": {
    homeTeam:"Mexico", awayTeam:"South Africa",
    homeFormation:"4-1-4-1", awayFormation:"5-3-2",
    homeStartXI:[
      {id:1,name:"Raúl Rangel",number:1,position:"GK"},
      {id:2,name:"Israel Reyes",number:15,position:"RB"},
      {id:3,name:"César Montes",number:3,position:"CB"},
      {id:4,name:"Johan Vásquez",number:5,position:"CB"},
      {id:5,name:"Jesús Gallardo",number:23,position:"LB"},
      {id:6,name:"Érik Lira",number:6,position:"DM"},
      {id:7,name:"Roberto Alvarado",number:25,position:"RM"},
      {id:8,name:"Álvaro Fidalgo",number:8,position:"CM"},
      {id:9,name:"Brian Gutiérrez",number:26,position:"CM"},
      {id:10,name:"Julián Quiñones",number:16,position:"LM"},
      {id:11,name:"Raúl Jiménez",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Edson Álvarez",number:4,position:"MF"},
      {id:13,name:"Luis Romo",number:7,position:"MF"},
      {id:14,name:"Santiago Giménez",number:11,position:"FW"},
      {id:15,name:"Alexis Vega",number:10,position:"FW"},
      {id:16,name:"Armando González",number:14,position:"FW"},
      {id:17,name:"Gilberto Mora",number:19,position:"MF"},
      {id:18,name:"Luis Chávez",number:24,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Ronwen Williams",number:1,position:"GK"},
      {id:21,name:"Nkosinathi Sibisi",number:19,position:"CB"},
      {id:22,name:"Ime Okon",number:21,position:"CB"},
      {id:23,name:"Mbekezeli Mbokazi",number:14,position:"CB"},
      {id:24,name:"Khuliso Mudau",number:20,position:"RB"},
      {id:25,name:"Aubrey Modiba",number:6,position:"LB"},
      {id:26,name:"Teboho Mokoena",number:4,position:"CM"},
      {id:27,name:"Sphephelo Sithole",number:13,position:"CM"},
      {id:28,name:"Jayden Adams",number:23,position:"CM"},
      {id:29,name:"Lyle Foster",number:9,position:"CF"},
      {id:30,name:"Iqraam Rayners",number:15,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Thalente Mbatha",number:5,position:"MF"},
      {id:32,name:"Themba Zwane",number:11,position:"MF"},
      {id:33,name:"Oswin Appollis",number:7,position:"FW"},
      {id:34,name:"Evidence Makgopa",number:17,position:"FW"},
    ],
  },
  "South Korea_Czech Republic": {
    homeTeam:"South Korea", awayTeam:"Czech Republic",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Kim Seung-gyu",number:1,position:"GK"},
      {id:2,name:"Kim Moon-hwan",number:2,position:"RB"},
      {id:3,name:"Kim Min-jae",number:3,position:"CB"},
      {id:4,name:"Jung Seung-hyun",number:4,position:"CB"},
      {id:5,name:"Kim Jin-su",number:5,position:"LB"},
      {id:6,name:"Hwang In-beom",number:6,position:"CM"},
      {id:7,name:"Jung Woo-young",number:7,position:"CM"},
      {id:8,name:"Lee Jae-sung",number:8,position:"CM"},
      {id:9,name:"Hwang Hee-chan",number:9,position:"RF"},
      {id:10,name:"Son Heung-min",number:10,position:"CF"},
      {id:11,name:"Na Sang-ho",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Cho Gue-sung",number:12,position:"FW"},
      {id:13,name:"Lee Kang-in",number:13,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Tomáš Vaclík",number:1,position:"GK"},
      {id:21,name:"Vladimir Coufal",number:2,position:"RB"},
      {id:22,name:"Tomáš Holeš",number:3,position:"CB"},
      {id:23,name:"Ondřej Kúdela",number:4,position:"CB"},
      {id:24,name:"Jan Bořil",number:5,position:"LB"},
      {id:25,name:"Tomáš Souček",number:6,position:"DM"},
      {id:26,name:"Alex Král",number:7,position:"DM"},
      {id:27,name:"Lukáš Provod",number:8,position:"RW"},
      {id:28,name:"Patrik Schick",number:9,position:"AM"},
      {id:29,name:"Ondřej Lingr",number:10,position:"LW"},
      {id:30,name:"Adam Hložek",number:11,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Jan Kuchta",number:12,position:"FW"},
      {id:32,name:"Marek Suchý",number:13,position:"DF"},
    ],
  },
  "Canada_Bosnia & Herzegovina": {
    homeTeam:"Canada", awayTeam:"Bosnia & Herzegovina",
    homeFormation:"4-4-2", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Maxime Crépeau",number:16,position:"GK"},
      {id:2,name:"Alistair Johnston",number:2,position:"RB"},
      {id:3,name:"Moïse Bombito",number:15,position:"CB"},
      {id:4,name:"Derek Cornelius",number:13,position:"CB"},
      {id:5,name:"Richie Laryea",number:22,position:"LB"},
      {id:6,name:"Tajon Buchanan",number:17,position:"RM"},
      {id:7,name:"Nathan Saliba",number:25,position:"CM"},
      {id:8,name:"Stephen Eustáquio",number:7,position:"CM"},
      {id:9,name:"Liam Millar",number:11,position:"LM"},
      {id:10,name:"Jonathan David",number:10,position:"CF"},
      {id:11,name:"Tani Oluwaseyi",number:12,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Alphonso Davies",number:19,position:"DF"},
      {id:13,name:"Jacob Shaffelburg",number:14,position:"MF"},
      {id:14,name:"Promise David",number:24,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Nikola Vasilj",number:1,position:"GK"},
      {id:21,name:"Amar Dedić",number:7,position:"RB"},
      {id:22,name:"Nikola Katić",number:18,position:"CB"},
      {id:23,name:"Tarik Muharemović",number:4,position:"CB"},
      {id:24,name:"Sead Kolašinac",number:5,position:"LB"},
      {id:25,name:"Armin Gigović",number:8,position:"RM"},
      {id:26,name:"Ivan Šunjić",number:14,position:"CM"},
      {id:27,name:"Kerim Alajbegović",number:19,position:"CM"},
      {id:28,name:"Esmir Bajraktarević",number:20,position:"LM"},
      {id:29,name:"Edin Džeko",number:11,position:"CF"},
      {id:30,name:"Ermedin Demirović",number:10,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Benjamin Tahirović",number:6,position:"MF"},
      {id:32,name:"Haris Tabaković",number:23,position:"FW"},
    ],
  },
  "Qatar_Switzerland": {
    homeTeam:"Qatar", awayTeam:"Switzerland",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Meshaal Barsham",number:1,position:"GK"},
      {id:2,name:"Pedro Miguel",number:2,position:"RB"},
      {id:3,name:"Tarek Salman",number:3,position:"CB"},
      {id:4,name:"Bassam Al-Rawi",number:4,position:"CB"},
      {id:5,name:"Homam Ahmed",number:5,position:"LB"},
      {id:6,name:"Karim Boudiaf",number:6,position:"CM"},
      {id:7,name:"Abdulaziz Hatem",number:7,position:"CM"},
      {id:8,name:"Hassan Al-Haydos",number:8,position:"CM"},
      {id:9,name:"Akram Afif",number:9,position:"RF"},
      {id:10,name:"Almoez Ali",number:10,position:"CF"},
      {id:11,name:"Mohammed Muntari",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Yusuf Abdurisag",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Gregor Kobel",number:1,position:"GK"},
      {id:21,name:"Denis Zakaria",number:6,position:"RB"},
      {id:22,name:"Nico Elvedi",number:4,position:"CB"},
      {id:23,name:"Manuel Akanji",number:5,position:"CB"},
      {id:24,name:"Ricardo Rodriguez",number:13,position:"LB"},
      {id:25,name:"Remo Freuler",number:8,position:"CM"},
      {id:26,name:"Granit Xhaka",number:10,position:"CM"},
      {id:27,name:"Dan Ndoye",number:11,position:"RW"},
      {id:28,name:"Johan Manzambi",number:9,position:"AM"},
      {id:29,name:"Rubén Vargas",number:17,position:"LW"},
      {id:30,name:"Breel Embolo",number:7,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Noah Okafor",number:19,position:"FW"},
      {id:32,name:"Fabian Rieder",number:22,position:"MF"},
    ],
  },
  "Brazil_Morocco": {
    homeTeam:"Brazil", awayTeam:"Morocco",
    homeFormation:"4-3-3", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Alisson",number:1,position:"GK"},
      {id:2,name:"Danilo Luiz",number:13,position:"RB"},
      {id:3,name:"Marquinhos",number:4,position:"CB"},
      {id:4,name:"Gabriel Magalhães",number:3,position:"CB"},
      {id:5,name:"Douglas Santos",number:16,position:"LB"},
      {id:6,name:"Casemiro",number:5,position:"DM"},
      {id:7,name:"Bruno Guimarães",number:8,position:"CM"},
      {id:8,name:"Lucas Paquetá",number:20,position:"CM"},
      {id:9,name:"Rayan",number:26,position:"RF"},
      {id:10,name:"Matheus Cunha",number:9,position:"CF"},
      {id:11,name:"Vinícius Júnior",number:7,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Endrick",number:19,position:"FW"},
      {id:13,name:"Gabriel Martinelli",number:22,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Yassine Bounou",number:1,position:"GK"},
      {id:21,name:"Achraf Hakimi",number:2,position:"RB"},
      {id:22,name:"Issa Diop",number:14,position:"CB"},
      {id:23,name:"Chadi Riad",number:18,position:"CB"},
      {id:24,name:"Noussair Mazraoui",number:3,position:"LB"},
      {id:25,name:"Ayyoub Bouaddi",number:6,position:"CM"},
      {id:26,name:"Neil El Aynaoui",number:24,position:"CM"},
      {id:27,name:"Brahim Díaz",number:10,position:"RW"},
      {id:28,name:"Azzedine Ounahi",number:8,position:"AM"},
      {id:29,name:"Bilal El Khannouss",number:23,position:"LW"},
      {id:30,name:"Ismael Saibari",number:11,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Soufiane Rahimi",number:9,position:"FW"},
      {id:32,name:"Chemsdine Talbi",number:7,position:"MF"},
    ],
  },
  "Haiti_Scotland": {
    homeTeam:"Haiti", awayTeam:"Scotland",
    homeFormation:"4-4-2", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Josué Duverger",number:1,position:"GK"},
      {id:2,name:"Mechack Jérôme",number:2,position:"RB"},
      {id:3,name:"Steeven Saba",number:3,position:"CB"},
      {id:4,name:"Zachary Herivaux",number:4,position:"CB"},
      {id:5,name:"Andrew Jean-Baptiste",number:5,position:"LB"},
      {id:6,name:"Duckens Nazon",number:6,position:"RM"},
      {id:7,name:"Wilde-Donald Guerrier",number:7,position:"CM"},
      {id:8,name:"Mickaël Biron",number:8,position:"CM"},
      {id:9,name:"Frantzdy Pierrot",number:9,position:"LM"},
      {id:10,name:"Carnejy Antoine",number:10,position:"CF"},
      {id:11,name:"Kevin Lafrance",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Derrick Étienne",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Angus Gunn",number:1,position:"GK"},
      {id:21,name:"Aaron Hickey",number:2,position:"RB"},
      {id:22,name:"Grant Hanley",number:3,position:"CB"},
      {id:23,name:"Scott McKenna",number:4,position:"CB"},
      {id:24,name:"Andrew Robertson",number:5,position:"LB"},
      {id:25,name:"Billy Gilmour",number:6,position:"CM"},
      {id:26,name:"John McGinn",number:7,position:"CM"},
      {id:27,name:"Stuart Armstrong",number:8,position:"CM"},
      {id:28,name:"Ryan Christie",number:9,position:"RW"},
      {id:29,name:"Che Adams",number:10,position:"CF"},
      {id:30,name:"Ryan Gauld",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Lyndon Dykes",number:12,position:"FW"},
      {id:32,name:"Kenny McLean",number:13,position:"MF"},
    ],
  },
  "USA_Paraguay": {
    homeTeam:"USA", awayTeam:"Paraguay",
    homeFormation:"3-4-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Matt Freese",number:24,position:"GK"},
      {id:2,name:"Alex Freeman",number:16,position:"CB"},
      {id:3,name:"Chris Richards",number:3,position:"CB"},
      {id:4,name:"Tim Ream",number:13,position:"CB"},
      {id:5,name:"Sergiño Dest",number:2,position:"RM"},
      {id:6,name:"Weston McKennie",number:8,position:"CM"},
      {id:7,name:"Tyler Adams",number:4,position:"CM"},
      {id:8,name:"Antonee Robinson",number:5,position:"LM"},
      {id:9,name:"Christian Pulisic",number:10,position:"RF"},
      {id:10,name:"Folarin Balogun",number:20,position:"CF"},
      {id:11,name:"Malik Tillman",number:17,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ricardo Pepi",number:9,position:"FW"},
      {id:13,name:"Giovanni Reyna",number:7,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Orlando Gill",number:12,position:"GK"},
      {id:21,name:"Juan José Cáceres",number:4,position:"RB"},
      {id:22,name:"Gustavo Gómez",number:15,position:"CB"},
      {id:23,name:"José Canale",number:13,position:"CB"},
      {id:24,name:"Júnior Alonso",number:6,position:"LB"},
      {id:25,name:"Miguel Almirón",number:10,position:"RM"},
      {id:26,name:"Damián Bobadilla",number:16,position:"CM"},
      {id:27,name:"Andrés Cubas",number:14,position:"CM"},
      {id:28,name:"Matías Galarza",number:23,position:"LM"},
      {id:29,name:"Gabriel Ávalos",number:21,position:"CF"},
      {id:30,name:"Julio Enciso",number:19,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Antonio Sanabria",number:9,position:"FW"},
      {id:32,name:"Maurício",number:11,position:"MF"},
    ],
  },
  "Australia_Turkey": {
    homeTeam:"Australia", awayTeam:"Turkey",
    homeFormation:"3-4-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Patrick Beach",number:18,position:"GK"},
      {id:2,name:"Alessandro Circati",number:3,position:"CB"},
      {id:3,name:"Harry Souttar",number:19,position:"CB"},
      {id:4,name:"Lucas Herrington",number:25,position:"CB"},
      {id:5,name:"Jordan Bos",number:5,position:"RM"},
      {id:6,name:"Jackson Irvine",number:22,position:"CM"},
      {id:7,name:"Aiden O\'Neill",number:13,position:"CM"},
      {id:8,name:"Aziz Behich",number:16,position:"LM"},
      {id:9,name:"Cristian Volpato",number:20,position:"RF"},
      {id:10,name:"Nestory Irankunda",number:17,position:"CF"},
      {id:11,name:"Connor Metcalfe",number:8,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ajdin Hrustic",number:10,position:"FW"},
      {id:13,name:"Mohamed Touré",number:9,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Altay Bayındır",number:1,position:"GK"},
      {id:21,name:"Zeki Çelik",number:2,position:"RB"},
      {id:22,name:"Merih Demiral",number:3,position:"CB"},
      {id:23,name:"Samet Akaydın",number:4,position:"CB"},
      {id:24,name:"Ferdi Kadıoğlu",number:5,position:"LB"},
      {id:25,name:"Hakan Çalhanoğlu",number:8,position:"DM"},
      {id:26,name:"Salih Özcan",number:6,position:"CM"},
      {id:27,name:"Kerem Aktürkoğlu",number:7,position:"RW"},
      {id:28,name:"Arda Güler",number:10,position:"AM"},
      {id:29,name:"Baris Alper Yilmaz",number:11,position:"LW"},
      {id:30,name:"Cenk Tosun",number:9,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Burak Yılmaz",number:12,position:"FW"},
      {id:32,name:"Okay Yokuşlu",number:13,position:"MF"},
    ],
  },
  "Germany_Curacao": {
    homeTeam:"Germany", awayTeam:"Curacao",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Manuel Neuer",number:1,position:"GK"},
      {id:2,name:"Joshua Kimmich",number:6,position:"RB"},
      {id:3,name:"Jonathan Tah",number:4,position:"CB"},
      {id:4,name:"Antonio Rüdiger",number:2,position:"CB"},
      {id:5,name:"Nathaniel Brown",number:18,position:"LB"},
      {id:6,name:"Felix Nmecha",number:23,position:"CM"},
      {id:7,name:"Aleksandar Pavlović",number:5,position:"CM"},
      {id:8,name:"Leroy Sané",number:19,position:"RW"},
      {id:9,name:"Kai Havertz",number:7,position:"AM"},
      {id:10,name:"Florian Wirtz",number:17,position:"LW"},
      {id:11,name:"Deniz Undav",number:26,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Leon Goretzka",number:8,position:"MF"},
      {id:13,name:"Jamal Musiala",number:10,position:"MF"},
      {id:14,name:"Nick Woltemade",number:11,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Eloy Room",number:1,position:"GK"},
      {id:21,name:"Cuco Martina",number:2,position:"RB"},
      {id:22,name:"Ethan Flemming",number:3,position:"CB"},
      {id:23,name:"Rangelo Janga",number:4,position:"CB"},
      {id:24,name:"Jurien Gaari",number:5,position:"LB"},
      {id:25,name:"Jarchinio Antonia",number:6,position:"CM"},
      {id:26,name:"Leandro Bacuna",number:7,position:"CM"},
      {id:27,name:"Cuco Martina Jr.",number:8,position:"CM"},
      {id:28,name:"Gevaro Nepomuceno",number:9,position:"RW"},
      {id:29,name:"Gino van Kessel",number:10,position:"CF"},
      {id:30,name:"Quentin Bautista",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Jafar Arias",number:12,position:"FW"},
    ],
  },
  "Netherlands_Japan": {
    homeTeam:"Netherlands", awayTeam:"Japan",
    homeFormation:"3-4-3", awayFormation:"3-4-3",
    homeStartXI:[
      {id:1,name:"Bart Verbruggen",number:1,position:"GK"},
      {id:2,name:"Jan Paul van Hecke",number:6,position:"CB"},
      {id:3,name:"Virgil van Dijk",number:4,position:"CB"},
      {id:4,name:"Nathan Aké",number:5,position:"CB"},
      {id:5,name:"Denzel Dumfries",number:22,position:"RM"},
      {id:6,name:"Ryan Gravenberch",number:8,position:"CM"},
      {id:7,name:"Frenkie de Jong",number:21,position:"CM"},
      {id:8,name:"Micky van de Ven",number:15,position:"LM"},
      {id:9,name:"Crysencio Summerville",number:24,position:"RF"},
      {id:10,name:"Brian Brobbey",number:19,position:"CF"},
      {id:11,name:"Cody Gakpo",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Teun Koopmeiners",number:20,position:"MF"},
      {id:13,name:"Wout Weghorst",number:9,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Zion Suzuki",number:1,position:"GK"},
      {id:21,name:"Takehiro Tomiyasu",number:22,position:"CB"},
      {id:22,name:"Shōgo Taniguchi",number:3,position:"CB"},
      {id:23,name:"Hiroki Itō",number:21,position:"CB"},
      {id:24,name:"Ritsu Dōan",number:10,position:"RM"},
      {id:25,name:"Kaishū Sano",number:24,position:"CM"},
      {id:26,name:"Daichi Kamada",number:15,position:"CM"},
      {id:27,name:"Keito Nakamura",number:13,position:"LM"},
      {id:28,name:"Junya Itō",number:14,position:"RF"},
      {id:29,name:"Ayase Ueda",number:18,position:"CF"},
      {id:30,name:"Daizen Maeda",number:11,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Ao Tanaka",number:7,position:"MF"},
      {id:32,name:"Kōki Ogawa",number:19,position:"FW"},
    ],
  },
  "Ivory Coast_Ecuador": {
    homeTeam:"Ivory Coast", awayTeam:"Ecuador",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Yahia Fofana",number:1,position:"GK"},
      {id:2,name:"Guéla Doué",number:17,position:"RB"},
      {id:3,name:"Odilon Kossounou",number:7,position:"CB"},
      {id:4,name:"Emmanuel Agbadou",number:20,position:"CB"},
      {id:5,name:"Ghislain Konan",number:3,position:"LB"},
      {id:6,name:"Ibrahim Sangaré",number:18,position:"DM"},
      {id:7,name:"Franck Kessié",number:8,position:"CM"},
      {id:8,name:"Nicolas Pépé",number:19,position:"RF"},
      {id:9,name:"Ange-Yoan Bonny",number:9,position:"CF"},
      {id:10,name:"Yan Diomande",number:11,position:"LF"},
      {id:11,name:"Christ Inao Oulaï",number:26,position:"CM"},
    ],
    homeSubs:[
      {id:12,name:"Amad Diallo",number:15,position:"FW"},
      {id:13,name:"Elye Wahi",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Hernán Galíndez",number:1,position:"GK"},
      {id:21,name:"Piero Hincapié",number:3,position:"LB"},
      {id:22,name:"Willian Pacho",number:6,position:"CB"},
      {id:23,name:"Joel Ordóñez",number:4,position:"CB"},
      {id:24,name:"Ángelo Preciado",number:17,position:"RB"},
      {id:25,name:"Moisés Caicedo",number:23,position:"CM"},
      {id:26,name:"Pedro Vite",number:15,position:"CM"},
      {id:27,name:"Nilson Angulo",number:20,position:"LM"},
      {id:28,name:"John Yeboah",number:9,position:"RM"},
      {id:29,name:"Gonzalo Plata",number:19,position:"CF"},
      {id:30,name:"Enner Valencia",number:13,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Kendry Páez",number:10,position:"MF"},
      {id:32,name:"Kevin Rodríguez",number:11,position:"FW"},
    ],
  },
  "Sweden_Tunisia": {
    homeTeam:"Sweden", awayTeam:"Tunisia",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Jacob Widell Zetterström",number:1,position:"GK"},
      {id:2,name:"Daniel Svensson",number:8,position:"RB"},
      {id:3,name:"Gustaf Lagerbielke",number:2,position:"CB"},
      {id:4,name:"Victor Lindelöf",number:3,position:"CB"},
      {id:5,name:"Gabriel Gudmundsson",number:5,position:"LB"},
      {id:6,name:"Anthony Elanga",number:11,position:"RM"},
      {id:7,name:"Lucas Bergvall",number:7,position:"CM"},
      {id:8,name:"Yasin Ayari",number:18,position:"CM"},
      {id:9,name:"Elliot Stroud",number:24,position:"LM"},
      {id:10,name:"Viktor Gyökeres",number:17,position:"CF"},
      {id:11,name:"Alexander Isak",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Taha Ali",number:26,position:"FW"},
      {id:13,name:"Besfort Zeneli",number:22,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Aymen Dahmen",number:1,position:"GK"},
      {id:21,name:"Mohamed Drager",number:2,position:"RB"},
      {id:22,name:"Montassar Talbi",number:3,position:"CB"},
      {id:23,name:"Yassine Meriah",number:4,position:"CB"},
      {id:24,name:"Ali Abdi",number:5,position:"LB"},
      {id:25,name:"Ellyes Skhiri",number:6,position:"CM"},
      {id:26,name:"Aissa Laidouni",number:7,position:"CM"},
      {id:27,name:"Wahbi Khazri",number:8,position:"CM"},
      {id:28,name:"Hannibal Mejbri",number:9,position:"RW"},
      {id:29,name:"Issam Jebali",number:10,position:"CF"},
      {id:30,name:"Seifeddine Jaziri",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Naïm Sliti",number:12,position:"MF"},
    ],
  },
  "Spain_Cape Verde": {
    homeTeam:"Spain", awayTeam:"Cape Verde",
    homeFormation:"4-3-3", awayFormation:"4-5-1",
    homeStartXI:[
      {id:1,name:"Unai Simón",number:23,position:"GK"},
      {id:2,name:"Pedro Porro",number:12,position:"RB"},
      {id:3,name:"Pau Cubarsí",number:22,position:"CB"},
      {id:4,name:"Aymeric Laporte",number:14,position:"CB"},
      {id:5,name:"Marc Cucurella",number:24,position:"LB"},
      {id:6,name:"Rodri",number:16,position:"DM"},
      {id:7,name:"Dani Olmo",number:10,position:"CM"},
      {id:8,name:"Pedri",number:20,position:"CM"},
      {id:9,name:"Lamine Yamal",number:19,position:"RF"},
      {id:10,name:"Mikel Oyarzabal",number:21,position:"CF"},
      {id:11,name:"Álex Baena",number:15,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ferran Torres",number:7,position:"FW"},
      {id:13,name:"Mikel Merino",number:6,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Vozinha",number:1,position:"GK"},
      {id:21,name:"Steven Moreira",number:22,position:"RB"},
      {id:22,name:"Pico",number:4,position:"CB"},
      {id:23,name:"Diney",number:3,position:"CB"},
      {id:24,name:"Sidny Lopes Cabral",number:13,position:"LB"},
      {id:25,name:"Kevin Pina",number:6,position:"DM"},
      {id:26,name:"Ryan Mendes",number:20,position:"RM"},
      {id:27,name:"Laros Duarte",number:15,position:"CM"},
      {id:28,name:"Deroy Duarte",number:14,position:"CM"},
      {id:29,name:"Jovane Cabral",number:7,position:"LM"},
      {id:30,name:"Nuno da Costa",number:21,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Jamiro Monteiro",number:10,position:"MF"},
      {id:32,name:"Dailon Livramento",number:19,position:"FW"},
    ],
  },
  "Belgium_Egypt": {
    homeTeam:"Belgium", awayTeam:"Egypt",
    homeFormation:"4-2-3-1", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Thibaut Courtois",number:1,position:"GK"},
      {id:2,name:"Timothy Castagne",number:21,position:"RB"},
      {id:3,name:"Brandon Mechele",number:4,position:"CB"},
      {id:4,name:"Arthur Theate",number:3,position:"CB"},
      {id:5,name:"Maxim De Cuyper",number:5,position:"LB"},
      {id:6,name:"Hans Vanaken",number:20,position:"CM"},
      {id:7,name:"Youri Tielemans",number:8,position:"CM"},
      {id:8,name:"Leandro Trossard",number:10,position:"RW"},
      {id:9,name:"Kevin De Bruyne",number:7,position:"AM"},
      {id:10,name:"Jérémy Doku",number:11,position:"LW"},
      {id:11,name:"Charles De Ketelaere",number:17,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Romelu Lukaku",number:9,position:"FW"},
      {id:13,name:"Dodi Lukébakio",number:14,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Mostafa Shobeir",number:23,position:"GK"},
      {id:21,name:"Mohamed Hany",number:3,position:"RB"},
      {id:22,name:"Yasser Ibrahim",number:2,position:"CB"},
      {id:23,name:"Ramy Rabia",number:5,position:"CB"},
      {id:24,name:"Karim Hafez",number:15,position:"LB"},
      {id:25,name:"Emam Ashour",number:8,position:"RM"},
      {id:26,name:"Hamdy Fathy",number:14,position:"CM"},
      {id:27,name:"Marwan Attia",number:19,position:"CM"},
      {id:28,name:"Mostafa Ziko",number:11,position:"LM"},
      {id:29,name:"Mohamed Salah",number:10,position:"CF"},
      {id:30,name:"Omar Marmoush",number:22,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Haissem Hassan",number:12,position:"FW"},
      {id:32,name:"Hossam Abdelmaguid",number:4,position:"DF"},
    ],
  },
  "Saudi Arabia_Uruguay": {
    homeTeam:"Saudi Arabia", awayTeam:"Uruguay",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Mohammed Al-Owais",number:1,position:"GK"},
      {id:2,name:"Saud Abdulhamid",number:2,position:"RB"},
      {id:3,name:"Ali Al-Bulaihi",number:3,position:"CB"},
      {id:4,name:"Abdulelah Al-Amri",number:4,position:"CB"},
      {id:5,name:"Yasser Al-Shahrani",number:5,position:"LB"},
      {id:6,name:"Salman Al-Faraj",number:6,position:"CM"},
      {id:7,name:"Abdulrahman Al-Aboud",number:7,position:"CM"},
      {id:8,name:"Sami Al-Naji",number:8,position:"CM"},
      {id:9,name:"Salem Al-Dawsari",number:9,position:"RW"},
      {id:10,name:"Firas Al-Buraikan",number:10,position:"CF"},
      {id:11,name:"Mohammed Al-Buraikan",number:11,position:"LW"},
    ],
    homeSubs:[
      {id:12,name:"Ali Al-Hassan",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Sergio Rochet",number:1,position:"GK"},
      {id:21,name:"Nahitan Nández",number:2,position:"RB"},
      {id:22,name:"José María Giménez",number:3,position:"CB"},
      {id:23,name:"Ronald Araújo",number:4,position:"CB"},
      {id:24,name:"Mathías Olivera",number:5,position:"LB"},
      {id:25,name:"Lucas Torreira",number:6,position:"DM"},
      {id:26,name:"Rodrigo Bentancur",number:7,position:"CM"},
      {id:27,name:"Federico Valverde",number:8,position:"CM"},
      {id:28,name:"Facundo Pellistri",number:9,position:"RW"},
      {id:29,name:"Darwin Núñez",number:10,position:"CF"},
      {id:30,name:"Maximiliano Araújo",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Edinson Cavani",number:12,position:"FW"},
      {id:32,name:"Giorgian de Arrascaeta",number:13,position:"MF"},
    ],
  },
  "Iran_New Zealand": {
    homeTeam:"Iran", awayTeam:"New Zealand",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Alireza Beiranvand",number:1,position:"GK"},
      {id:2,name:"Sadegh Moharrami",number:2,position:"RB"},
      {id:3,name:"Shoja Khalilzadeh",number:3,position:"CB"},
      {id:4,name:"Morteza Pouraliganji",number:4,position:"CB"},
      {id:5,name:"Milad Mohammadi",number:5,position:"LB"},
      {id:6,name:"Saeid Ezatolahi",number:6,position:"CM"},
      {id:7,name:"Mehdi Torabi",number:7,position:"CM"},
      {id:8,name:"Ali Karimi",number:8,position:"CM"},
      {id:9,name:"Sardar Azmoun",number:9,position:"RF"},
      {id:10,name:"Mehdi Taremi",number:10,position:"CF"},
      {id:11,name:"Allahyar Sayyadmanesh",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Ahmad Noorollahi",number:12,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Oliver Sail",number:1,position:"GK"},
      {id:21,name:"Liberato Cacace",number:2,position:"RB"},
      {id:22,name:"Niko Kirwan",number:3,position:"CB"},
      {id:23,name:"Winston Reid",number:4,position:"CB"},
      {id:24,name:"Michael Boxall",number:5,position:"LB"},
      {id:25,name:"Marko Stamenic",number:6,position:"CM"},
      {id:26,name:"Liam McGing",number:7,position:"CM"},
      {id:27,name:"Clayton Lewis",number:8,position:"CM"},
      {id:28,name:"Elijah Just",number:9,position:"RW"},
      {id:29,name:"Chris Wood",number:10,position:"CF"},
      {id:30,name:"Ben Old",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Kosta Barbarouses",number:12,position:"FW"},
    ],
  },
  "France_Senegal": {
    homeTeam:"France", awayTeam:"Senegal",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Mike Maignan",number:16,position:"GK"},
      {id:2,name:"Jules Koundé",number:5,position:"RB"},
      {id:3,name:"Dayot Upamecano",number:4,position:"CB"},
      {id:4,name:"William Saliba",number:17,position:"CB"},
      {id:5,name:"Lucas Digne",number:3,position:"LB"},
      {id:6,name:"Aurélien Tchouaméni",number:8,position:"CM"},
      {id:7,name:"Adrien Rabiot",number:14,position:"CM"},
      {id:8,name:"Ousmane Dembélé",number:7,position:"RW"},
      {id:9,name:"Michael Olise",number:11,position:"AM"},
      {id:10,name:"Bradley Barcola",number:12,position:"LW"},
      {id:11,name:"Kylian Mbappé",number:10,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Désiré Doué",number:20,position:"FW"},
      {id:13,name:"Rayan Cherki",number:24,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Mory Diaw",number:23,position:"GK"},
      {id:21,name:"Krépin Diatta",number:15,position:"RB"},
      {id:22,name:"Pathé Ciss",number:6,position:"CB"},
      {id:23,name:"Moussa Niakhaté",number:19,position:"CB"},
      {id:24,name:"Ismail Jakobs",number:14,position:"LB"},
      {id:25,name:"Habib Diarra",number:21,position:"CM"},
      {id:26,name:"Idrissa Gueye",number:5,position:"CM"},
      {id:27,name:"Pape Gueye",number:26,position:"CM"},
      {id:28,name:"Iliman Ndiaye",number:13,position:"RF"},
      {id:29,name:"Ismaïla Sarr",number:18,position:"CF"},
      {id:30,name:"Sadio Mané",number:10,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Lamine Camara",number:8,position:"MF"},
      {id:32,name:"Nicolas Jackson",number:11,position:"FW"},
    ],
  },
  "Iraq_Norway": {
    homeTeam:"Iraq", awayTeam:"Norway",
    homeFormation:"4-4-2", awayFormation:"4-2-3-1",
    homeStartXI:[
      {id:1,name:"Jalal Hassan",number:1,position:"GK"},
      {id:2,name:"Ali Adnan",number:2,position:"LB"},
      {id:3,name:"Salam Shakir",number:3,position:"CB"},
      {id:4,name:"Hussein Ali",number:4,position:"CB"},
      {id:5,name:"Ali Jasim",number:5,position:"RB"},
      {id:6,name:"Amjed Attwan",number:6,position:"RM"},
      {id:7,name:"Bashar Resan",number:7,position:"CM"},
      {id:8,name:"Aymen Hussein",number:8,position:"CM"},
      {id:9,name:"Ibrahim Bayesh",number:9,position:"LM"},
      {id:10,name:"Mohanad Ali",number:10,position:"CF"},
      {id:11,name:"Ahmed Yasin",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Alaa Abbas",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Ørjan Nyland",number:1,position:"GK"},
      {id:21,name:"Marcus Holmgren Pedersen",number:16,position:"RB"},
      {id:22,name:"Kristoffer Ajer",number:3,position:"CB"},
      {id:23,name:"Torbjørn Heggem",number:17,position:"CB"},
      {id:24,name:"David Møller Wolfe",number:5,position:"LB"},
      {id:25,name:"Patrick Berg",number:6,position:"CM"},
      {id:26,name:"Sander Berge",number:8,position:"CM"},
      {id:27,name:"Martin Ødegaard",number:10,position:"AM"},
      {id:28,name:"Alexander Sørloth",number:7,position:"RF"},
      {id:29,name:"Erling Haaland",number:9,position:"CF"},
      {id:30,name:"Antonio Nusa",number:20,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Oscar Bobb",number:22,position:"MF"},
      {id:32,name:"Andreas Schjelderup",number:21,position:"MF"},
    ],
  },
  "Argentina_Algeria": {
    homeTeam:"Argentina", awayTeam:"Algeria",
    homeFormation:"4-2-3-1", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Emiliano Martínez",number:23,position:"GK"},
      {id:2,name:"Nahuel Molina",number:26,position:"RB"},
      {id:3,name:"Cristian Romero",number:13,position:"CB"},
      {id:4,name:"Lisandro Martínez",number:6,position:"CB"},
      {id:5,name:"Facundo Medina",number:25,position:"LB"},
      {id:6,name:"Rodrigo De Paul",number:7,position:"RM"},
      {id:7,name:"Alexis Mac Allister",number:20,position:"CM"},
      {id:8,name:"Enzo Fernández",number:24,position:"CM"},
      {id:9,name:"Thiago Almada",number:16,position:"LM"},
      {id:10,name:"Lionel Messi",number:10,position:"CF"},
      {id:11,name:"Lautaro Martínez",number:22,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Julián Alvarez",number:9,position:"FW"},
      {id:13,name:"Leandro Paredes",number:5,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Luca Zidane",number:23,position:"GK"},
      {id:21,name:"Rafik Belghali",number:17,position:"RB"},
      {id:22,name:"Aïssa Mandi",number:2,position:"CB"},
      {id:23,name:"Ramy Bensebaini",number:21,position:"CB"},
      {id:24,name:"Rayan Aït-Nouri",number:15,position:"LB"},
      {id:25,name:"Nabil Bentaleb",number:19,position:"DM"},
      {id:26,name:"Ramiz Zerrouki",number:6,position:"CM"},
      {id:27,name:"Farès Chaïbi",number:10,position:"CM"},
      {id:28,name:"Riyad Mahrez",number:7,position:"RF"},
      {id:29,name:"Ibrahim Maza",number:22,position:"CF"},
      {id:30,name:"Houssem Aouar",number:8,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Amine Gouiri",number:9,position:"FW"},
      {id:32,name:"Anis Hadj Moussa",number:11,position:"FW"},
    ],
  },
  "Austria_Jordan": {
    homeTeam:"Austria", awayTeam:"Jordan",
    homeFormation:"4-2-3-1", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Alexander Schlager",number:1,position:"GK"},
      {id:2,name:"Stefan Posch",number:5,position:"RB"},
      {id:3,name:"Kevin Danso",number:3,position:"CB"},
      {id:4,name:"David Alaba",number:8,position:"CB"},
      {id:5,name:"Konrad Laimer",number:20,position:"LB"},
      {id:6,name:"Nicolas Seiwald",number:6,position:"CM"},
      {id:7,name:"Xaver Schlager",number:4,position:"CM"},
      {id:8,name:"Romano Schmid",number:18,position:"RW"},
      {id:9,name:"Paul Wanner",number:24,position:"AM"},
      {id:10,name:"Marcel Sabitzer",number:9,position:"LW"},
      {id:11,name:"Michael Gregoritsch",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Marko Arnautović",number:7,position:"FW"},
      {id:13,name:"Florian Grillitsch",number:10,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Yazeed Abulaila",number:1,position:"GK"},
      {id:21,name:"Baha Faisal",number:2,position:"RB"},
      {id:22,name:"Anas Bani Yaseen",number:3,position:"CB"},
      {id:23,name:"Yazan Al-Naimat",number:4,position:"CB"},
      {id:24,name:"Ahmad Ibrahim",number:5,position:"LB"},
      {id:25,name:"Nizar Al-Rashdan",number:6,position:"CM"},
      {id:26,name:"Musa Al-Tamari",number:7,position:"CM"},
      {id:27,name:"Salem Al-Ajalin",number:8,position:"CM"},
      {id:28,name:"Hamza Al-Dardour",number:9,position:"RW"},
      {id:29,name:"Yazan Al-Arab",number:10,position:"CF"},
      {id:30,name:"Zaid Al-Rashdan",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Ahmad Habashneh",number:12,position:"FW"},
    ],
  },
  "Portugal_D.R. Congo": {
    homeTeam:"Portugal", awayTeam:"D.R. Congo",
    homeFormation:"4-3-3", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Diogo Costa",number:1,position:"GK"},
      {id:2,name:"João Cancelo",number:20,position:"RB"},
      {id:3,name:"Rúben Dias",number:3,position:"CB"},
      {id:4,name:"Renato Veiga",number:13,position:"CB"},
      {id:5,name:"Nuno Mendes",number:25,position:"LB"},
      {id:6,name:"João Neves",number:15,position:"CM"},
      {id:7,name:"Vitinha",number:23,position:"CM"},
      {id:8,name:"Bruno Fernandes",number:8,position:"AM"},
      {id:9,name:"Pedro Neto",number:18,position:"RW"},
      {id:10,name:"Rafael Leão",number:17,position:"LW"},
      {id:11,name:"Cristiano Ronaldo",number:7,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Gonçalo Ramos",number:9,position:"FW"},
      {id:13,name:"Bernardo Silva",number:10,position:"MF"},
    ],
    awayStartXI:[
      {id:20,name:"Lionel Mpasi",number:1,position:"GK"},
      {id:21,name:"Aaron Wan-Bissaka",number:2,position:"RB"},
      {id:22,name:"Chancel Mbemba",number:22,position:"CB"},
      {id:23,name:"Axel Tuanzebe",number:4,position:"CB"},
      {id:24,name:"Arthur Masuaku",number:26,position:"LB"},
      {id:25,name:"Samuel Moutoussamy",number:8,position:"DM"},
      {id:26,name:"Nathanaël Mbuku",number:7,position:"RM"},
      {id:27,name:"Ngal\'ayel Mukau",number:6,position:"CM"},
      {id:28,name:"Noah Sadiki",number:14,position:"CM"},
      {id:29,name:"Brian Cipenga",number:9,position:"LM"},
      {id:30,name:"Yoane Wissa",number:20,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Meschak Elia",number:13,position:"FW"},
      {id:32,name:"Théo Bongonda",number:10,position:"MF"},
    ],
  },
  "England_Croatia": {
    homeTeam:"England", awayTeam:"Croatia",
    homeFormation:"4-3-3", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Jordan Pickford",number:1,position:"GK"},
      {id:2,name:"Djed Spence",number:25,position:"RB"},
      {id:3,name:"Ezri Konsa",number:2,position:"CB"},
      {id:4,name:"Marc Guéhi",number:6,position:"CB"},
      {id:5,name:"Nico O'Reilly",number:3,position:"LB"},
      {id:6,name:"Elliot Anderson",number:8,position:"CM"},
      {id:7,name:"Declan Rice",number:4,position:"CM"},
      {id:8,name:"Noni Madueke",number:20,position:"RW"},
      {id:9,name:"Jude Bellingham",number:10,position:"AM"},
      {id:10,name:"Marcus Rashford",number:11,position:"LW"},
      {id:11,name:"Harry Kane",number:9,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Bukayo Saka",number:7,position:"FW"},
      {id:13,name:"Anthony Gordon",number:18,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Dominik Livaković",number:1,position:"GK"},
      {id:21,name:"Josip Stanišić",number:2,position:"RB"},
      {id:22,name:"Josip Šutalo",number:6,position:"CB"},
      {id:23,name:"Marin Pongračić",number:3,position:"CB"},
      {id:24,name:"Ivan Perišić",number:14,position:"LB"},
      {id:25,name:"Luka Modrić",number:10,position:"CM"},
      {id:26,name:"Mateo Kovačić",number:8,position:"CM"},
      {id:27,name:"Nikola Vlašić",number:13,position:"RW"},
      {id:28,name:"Petar Sučić",number:17,position:"AM"},
      {id:29,name:"Martin Baturina",number:16,position:"LW"},
      {id:30,name:"Ante Budimir",number:11,position:"CF"},
    ],
    awaySubs:[
      {id:31,name:"Igor Matanović",number:20,position:"FW"},
      {id:32,name:"Mario Pašalić",number:15,position:"MF"},
    ],
  },
  "Ghana_Panama": {
    homeTeam:"Ghana", awayTeam:"Panama",
    homeFormation:"4-5-1", awayFormation:"4-4-2",
    homeStartXI:[
      {id:1,name:"Lawrence Ati-Zigi",number:1,position:"GK"},
      {id:2,name:"Marvin Senaya",number:26,position:"RB"},
      {id:3,name:"Derrick Luckassen",number:23,position:"CB"},
      {id:4,name:"Jerome Opoku",number:18,position:"CB"},
      {id:5,name:"Gideon Mensah",number:14,position:"LB"},
      {id:6,name:"Thomas Partey",number:5,position:"DM"},
      {id:7,name:"Caleb Yirenkyi",number:3,position:"CM"},
      {id:8,name:"Kwasi Sibo",number:8,position:"CM"},
      {id:9,name:"Iñaki Williams",number:19,position:"RF"},
      {id:10,name:"Jordan Ayew",number:9,position:"CF"},
      {id:11,name:"Antoine Semenyo",number:11,position:"LF"},
    ],
    homeSubs:[
      {id:12,name:"Abdul Fatawu",number:7,position:"FW"},
      {id:13,name:"Ernest Nuamah",number:24,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Orlando Mosquera",number:1,position:"GK"},
      {id:21,name:"Fidel Escobar",number:2,position:"RB"},
      {id:22,name:"Andrés Andrade",number:3,position:"CB"},
      {id:23,name:"Harold Cummings",number:4,position:"CB"},
      {id:24,name:"Éric Davis",number:5,position:"LB"},
      {id:25,name:"Adalberto Carrasquilla",number:6,position:"CM"},
      {id:26,name:"José Fajardo",number:7,position:"CM"},
      {id:27,name:"Roderick Miller",number:8,position:"CM"},
      {id:28,name:"Cecilio Waterman",number:9,position:"RW"},
      {id:29,name:"Ismael Díaz",number:10,position:"CF"},
      {id:30,name:"José Luis Rodríguez",number:11,position:"LW"},
    ],
    awaySubs:[
      {id:31,name:"Gabriel Torres",number:12,position:"FW"},
    ],
  },
  "Uzbekistan_Colombia": {
    homeTeam:"Uzbekistan", awayTeam:"Colombia",
    homeFormation:"4-4-2", awayFormation:"4-3-3",
    homeStartXI:[
      {id:1,name:"Abduvohid Nishonov",number:1,position:"GK"},
      {id:2,name:"Sherzod Nasrullayev",number:2,position:"RB"},
      {id:3,name:"Abbosbek Fayzullayev",number:3,position:"CB"},
      {id:4,name:"Shamsiddin Latipov",number:4,position:"CB"},
      {id:5,name:"Dostonbek Khamdamov",number:5,position:"LB"},
      {id:6,name:"Jamshid Iskanderov",number:6,position:"RM"},
      {id:7,name:"Bobur Abdixoliqov",number:7,position:"CM"},
      {id:8,name:"Otabek Shukurov",number:8,position:"CM"},
      {id:9,name:"Eldor Shomurodov",number:9,position:"LM"},
      {id:10,name:"Nodir Tursunov",number:10,position:"CF"},
      {id:11,name:"Ilhomjon Hamroyev",number:11,position:"CF"},
    ],
    homeSubs:[
      {id:12,name:"Akbar Hamroyev",number:12,position:"FW"},
    ],
    awayStartXI:[
      {id:20,name:"Camilo Vargas",number:12,position:"GK"},
      {id:21,name:"Daniel Muñoz",number:2,position:"RB"},
      {id:22,name:"Davinson Sánchez",number:23,position:"CB"},
      {id:23,name:"Jhon Lucumí",number:3,position:"CB"},
      {id:24,name:"Johan Mojica",number:17,position:"LB"},
      {id:25,name:"Jefferson Lerma",number:16,position:"DM"},
      {id:26,name:"Gustavo Puerta",number:14,position:"CM"},
      {id:27,name:"Jhon Arias",number:11,position:"CM"},
      {id:28,name:"James Rodríguez",number:10,position:"RF"},
      {id:29,name:"Jhon Córdoba",number:9,position:"CF"},
      {id:30,name:"Luis Díaz",number:7,position:"LF"},
    ],
    awaySubs:[
      {id:31,name:"Luis Suárez",number:25,position:"FW"},
      {id:32,name:"Richard Ríos",number:6,position:"MF"},
    ],
  },
'''

old = "export const HARDCODED_LINEUPS: Record<string, MatchLineup> = {"
new = "export const HARDCODED_LINEUPS: Record<string, MatchLineup> = {" + group_lineups

if old in content:
    content = content.replace(old, new, 1)
    with open('src/services/footballData.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Done - added matchday 1 lineups (24 matches)')
else:
    print('ERROR: marker not found')
